KCRO-56: add ability to set and get i18n icon and screenshots for UI apps
2600hz/kazoo-crossbar pull request #119
Opened 2021-01-14 04:56 UTC by icehess

2021-02-20 22:20 UTC, icehess commented
### Required PR:
* allow numbers in cb modules: https://github.com/2600hz/kazoo-ast/pull/11
* kzd_app accessors: https://github.com/2600hz/kazoo-core/pull/196
* https://github.com/2600hz/kazoo-core/pull/216

2021-02-22 18:37 UTC, jamesaimonetti requested changes

2021-02-22 18:37 UTC, jamesaimonetti commented on src/cb_apps_util.erl
> +               || JObj <- JObjs,
You can "cheat" by putting the get_json_value into another generator:
```erlang
[{kz_doc:id(JObj, Doc} || JObj <- JObjs, Doc <- [kz_json:get_json_value(<<"doc">>, JObj)], Doc =/= 'undefined']
```

2021-02-22 18:37 UTC, jamesaimonetti commented on src/cb_apps_util.erl
> +      [{kz_doc:id(JObjs), ensure_master_account_id(MasterAccountDb, kz_json:get_value(<<"doc">>, JObj, JObj))}
Should be `kz_doc:id(JObj)` right? JObj not JObjs?

2021-02-22 18:37 UTC, jamesaimonetti commented on src/modules/cb_apps_store.erl
> +    cb_context:save(cb_context:set_doc(kz_doc:delete_attachment(JObj, AttachmentId))).
`cb_context:save/1` doesn't exist?

2021-02-22 18:37 UTC, jamesaimonetti commented on src/modules/cb_apps_store.erl
> +    cb_context:save(cb_context:set_doc(kz_doc:delete_attachment(JObj, AttachmentId))).
`cb_context:set_doc/1` doesn't exist either?

2021-02-23 06:26 UTC, icehess commented
New requirement: https://github.com/2600hz/kazoo-core/pull/216

2021-02-24 18:57 UTC, icehess commented on src/modules/cb_apps_store.erl
> +    cb_context:save(cb_context:set_doc(kz_doc:delete_attachment(JObj, AttachmentId))).
fixed

2021-02-24 18:57 UTC, icehess commented on src/cb_apps_util.erl
> +      [{kz_doc:id(JObjs), ensure_master_account_id(MasterAccountDb, kz_json:get_value(<<"doc">>, JObj, JObj))}
fixed

2021-02-24 18:58 UTC, icehess commented on src/cb_apps_util.erl
> +               || JObj <- JObjs,
I was trying to not cheat this time but anyway I changed it.

2021-03-08 20:48 UTC, merged