KZOO-120: Add carrier ACL when a local carrier is added.
2600hz/kazoo-crossbar pull request #123
Opened 2021-01-15 20:48 UTC by holy-batman

2021-01-27 23:40 UTC, lazedo requested changes
reload should be done on successful completion, not on each doc (in case of collection)

2021-01-27 23:40 UTC, lazedo commented on src/modules/cb_resources.erl
> +    _ = reload_trusted(),
reload should be done on success not before

2021-01-27 23:40 UTC, lazedo commented on src/modules/cb_resources.erl
> +    _ = reload_trusted(),
reload should be done `once` on successful completion

2021-01-27 23:40 UTC, lazedo commented on src/modules/cb_resources.erl
> -    maybe_reload_acls(cb_context:db_name(Context)),
processing a collection the way it is now would `reload` the number of the docs

2021-01-28 17:15 UTC, holy-batman commented on src/modules/cb_resources.erl
> +    _ = reload_trusted(),
changed to only refresh if success.

2021-01-28 17:16 UTC, holy-batman commented on src/modules/cb_resources.erl
> -    maybe_reload_acls(cb_context:db_name(Context)),
changed collection refresh to be done after a success is received from collection.

2021-01-28 18:16 UTC, lazedo approved these changes

2021-01-28 18:22 UTC, jamesaimonetti requested changes

2021-01-28 18:22 UTC, jamesaimonetti commented on src/modules/cb_resources.erl
> +    _ = aggregate_resource([ResourceJObj]),
Why wrap this in a list? Shouldn't `aggregate_resource/1` take a JSON object only, not a list of JSON objects?

And I'd rather just call `lists:foreach/2` here:

```erlang
maybe_aggregate_resources(ResourceJObjs) ->
    lists:foreach(fun aggregate_resource/1, ResourceJObjs).
```

2021-01-28 18:27 UTC, holy-batman commented on src/modules/cb_resources.erl
> +    _ = aggregate_resource([ResourceJObj]),
@jamesaimonetti fixed :)

2021-01-28 19:24 UTC, merged