First Version of screenpops API
2600hz/kazoo-crossbar pull request #206
Opened 2021-08-19 19:34 UTC by kdamas93

-First Version of screenpops API

2021-08-19 21:00 UTC, jamesaimonetti commented on priv/couchdb/views/screenpops.json
> +                "    'id': doc._id,",
id is included on all view results, no need to include it in the view as well. You'll get "key", "value" (the emitted object here), and "id" I believe.

2021-08-19 21:01 UTC, jamesaimonetti commented on src/modules/cb_screenpops.erl
> +validate(Context, _DocId) ->
Change to `_ScreenpopId` (and try not to use `_` in function args; we still like to see what the value represents). But in this case, tooling uses the variable name for doc generation.

2021-08-19 22:16 UTC, kdamas93 commented on src/modules/cb_screenpops.erl
> +validate(Context, _DocId) ->
Changed ! Ty.

2021-08-19 22:20 UTC, kdamas93 commented on priv/couchdb/views/screenpops.json
> +                "    'id': doc._id,",
Id is needed when we do a get all

2021-08-19 23:39 UTC, jamesaimonetti commented on doc/screenpops.md
> +> GET /v2/accounts/{ACCOUNT_ID}/screenpops
Can you include expected JSON responses for all requests and sample JSON request data for PUT/POST/etc?

2021-08-19 23:40 UTC, jamesaimonetti commented on priv/couchdb/schemas/screenpops_config.json
> +    "_id": "screenpops_config",
I question why `screenpops_config` vs `screenpops`?

For most of the API schemas, if the endpoint is `users` then the schema matches.

2021-08-19 23:41 UTC, jamesaimonetti commented on priv/couchdb/schemas/screenpops_config.json
> +    "_id": "screenpops_config",
Would also help to get a `kzd_screenpops.erl` accessor module in `core/kazoo_documents`

2021-08-19 23:41 UTC, jamesaimonetti commented on priv/oas3/oas3-parameters.yml
> +'DOC_ID':
remove this so it can get re-generated with `SCREENPOP_ID` or whatever the tooling decides

2021-08-19 23:42 UTC, jamesaimonetti commented on priv/oas3/openapi.yml
> +  '/accounts/{ACCOUNT_ID}/screenpops/{DOC_ID}':
Same here

2021-08-19 23:43 UTC, jamesaimonetti commented on src/modules/cb_screenpops.erl
> +    cb_context:set_doc(Context, kz_json:set_values([{<<"pvt_type">>, <<"screenpops_config">>}
`pvt_type` should probably be `screenpop` to match project standards.

2021-08-23 19:52 UTC, kdamas93 commented on src/modules/cb_screenpops.erl
> +    cb_context:set_doc(Context, kz_json:set_values([{<<"pvt_type">>, <<"screenpops_config">>}
changed, tyvm for the explanation

2021-08-23 21:20 UTC, jamesaimonetti commented on src/modules/cb_screenpops.erl
> +allowed_methods(_DocId) ->
I think this is causing `DocId` in the docs to be generated. Make sure all instances in the code are changed to `_ScreenpopId` or `ScreenpopId` as needed.

2021-08-24 12:31 UTC, kdamas93 commented on src/modules/cb_screenpops.erl
> +allowed_methods(_DocId) ->
Changed! Tyvm

2021-08-25 15:48 UTC, jamesaimonetti requested changes

2021-08-25 15:48 UTC, jamesaimonetti commented on doc/screenpops.md
> +#### About Screenpops
Can you add some text about what this API would be used for? Also, I think you need to rename the schema from `screenpops_config.json` to `screenpops.json`. You should then get a markdown table with the schema inserted into the doc (and ref doc).

2021-08-25 15:48 UTC, jamesaimonetti commented on priv/couchdb/schemas/screenpops_config.json
> +                    "type": "string"
Add basic `"description":"what is this field even?"` properties

2021-08-25 15:49 UTC, jamesaimonetti commented
One more thing - the schema will generate a file in `/core/kazoo_documents/` that will need its own PR. Copy the `screenpop.erl.src` file to `screenpop.erl` and flesh out any functions needed.

2021-08-26 19:43 UTC, kdamas93 commented on doc/screenpops.md
> +#### About Screenpops
Explanation added and file renamed

2021-08-26 19:43 UTC, kdamas93 commented on priv/couchdb/schemas/screenpops_config.json
> +                    "type": "string"
Description added

2021-08-27 20:43 UTC, jamesaimonetti commented
See:
- https://github.com/2600hz/kazoo-core/pull/296
- https://github.com/2600hz/kazoo-properly/pull/63

2021-08-30 20:30 UTC, merged