Adding endpoint to generate token to login into getstreamio API
2600hz/kazoo-crossbar pull request #221
Opened 2021-10-12 21:00 UTC by kdamas93

2021-10-13 13:46 UTC, icehess requested changes
Left some comments regarding secret/private_key.

Another question, what is this `TokenId` use for?

2021-10-13 13:46 UTC, icehess commented on src/modules/cb_getstream.erl
> +    kapps_config:get_ne_binary(<<(?CONFIG_CAT)/binary, ".getstream">>, <<"secret">>, <<"">>).
Remove `<<"">>`, otherwise it never returns `undefined` and we always create JWT with an empty secret.

2021-10-13 13:46 UTC, icehess commented on src/modules/cb_getstream.erl
> +                     key => Secret}
looking at `kz)auth_jwt` it seems key is a Private Key. Is the secret is in form of Pem? you also need to decode it. When signing the JWT it uses `public_key:sign/3` which is expecting a decoded private key.

2021-10-13 22:09 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    kapps_config:get_ne_binary(<<(?CONFIG_CAT)/binary, ".getstream">>, <<"secret">>, <<"">>).
That's the intention to create a placeholder, this secret key will be added manually or by cluster manager

2021-10-14 14:51 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +                     key => Secret}
The key that will be saved in the doc is already decode, is the way that getsream sent to us, I did tests passing that key to sign/3, the connection was successful.
There is already a PR related to this implementation : https://github.com/2600hz/kazoo-core/pull/311
We will use crypto:mac because getstream works with hs256 alg.

2021-10-14 15:07 UTC, kdamas93 commented
> Left some comments regarding secret/private_key.
> 
> Another question, what is this `TokenId` use for?

Is been using just to be located in the response

2021-10-14 23:40 UTC, jamesaimonetti commented
@kdamas93 you should run `make ci-codechecks` from the kazoo root.

Missing files include:
- `doc/ref/getstream.md` which is the auto-generated API doc page
- `priv/couchdb/schemas/system_config.crossbar.getstream.json` - the schema file for the system config doc
- `priv/oas3/paths/getstream.yml`

I suspect CI checks aren't errors on untracked files generated. Will check why this PR is considered passing in that case.

2021-10-15 20:08 UTC, kdamas93 commented
Files added ! Thanks for your help @jamesaimonetti

2021-10-18 16:14 UTC, jamesaimonetti commented on doc/ref/getstream.md
> +> PUT /v2/accounts/{ACCOUNT_ID}/getstream/token
Can you sync up the docs to match. Headings should start with a single `#` then nest further, for instance.

2021-10-20 16:24 UTC, jamesaimonetti commented on doc/getstream.md
> +#### About Getstream Token
Please match headings to the ref doc (this should be `##` for instance)

2021-10-22 20:25 UTC, merged