KCAL-33: Include branch_extension documention for menus
2600hz/kazoo-crossbar pull request #241
Opened 2022-02-05 01:34 UTC by harenson

Related PR: https://github.com/2600hz/kazoo-callflow/pull/103
Depends on: https://github.com/2600hz/kazoo-core/pull/373

2022-02-05 10:01 UTC, lazedo requested changes

2022-02-05 10:01 UTC, lazedo commented on priv/api/swagger.json
> +                    "default": false,
why is this changing ?

2022-02-07 18:43 UTC, harenson commented on priv/api/swagger.json
> +                    "default": false,
Because when you create a new menu, that value is false by default.

2022-02-07 19:14 UTC, lazedo commented on priv/api/swagger.json
> +                    "default": false,
and when did that changed without updating this ? afaics, its not related to this pr

2022-02-07 19:26 UTC, harenson commented on priv/api/swagger.json
> +                    "default": false,
I just reverted that change.

2022-02-08 00:10 UTC, lazedo commented
@harenson i think that `stop_after_extension` is not correct as the executing may not call `cf_exe:stop/1`, we should use `branch_extension` (or some rewording around that) that would reflect what we really do, ie, **branch** or **continue**

2022-02-11 03:26 UTC, harenson commented
@lazedo Yes, makes sense.

2022-02-14 09:53 UTC, merged