[master] SHIP-42: Commland compatibility api added for version compatible client selection
2600hz/kazoo-crossbar pull request #297
Opened 2022-06-22 13:17 UTC by swysor

2022-06-22 21:21 UTC, jamesaimonetti requested changes

2022-06-22 21:21 UTC, jamesaimonetti commented on src/modules/cb_commland.erl
> +authorize(Context, _) ->
It seems only `/commland/compatibility` is the supported path so I would make this clause explicit: `authorize(Context, ?COMPAT) ->` and remove the `authorize/3` function. Similar change for authenticate

2022-06-22 21:21 UTC, jamesaimonetti commented on src/modules/cb_commland.erl
> +authorize_commland(_, ?HTTP_GET, ?COMPAT_NOUNS) ->
In general, we try not to use `_` in function heads, just prefix the variable name with `_` (like `_Context` in this case).

2022-06-22 21:21 UTC, jamesaimonetti commented on src/modules/cb_commland.erl
> +resource_exists() -> 'true'.
Similar here; the only really valid path appears to be `/commland/compatibility` so remove functions that should never be called.

2022-06-22 21:21 UTC, jamesaimonetti commented on src/modules/cb_commland.erl
> +    validate_commland(cb_context:set_db_name(Context, ?KZ_WEBHOOKS_DB), cb_context:req_verb(Context)).
Why setting the db name to webhooks?

2022-06-23 17:08 UTC, swysor commented on src/modules/cb_commland.erl
> +    validate_commland(cb_context:set_db_name(Context, ?KZ_WEBHOOKS_DB), cb_context:req_verb(Context)).
d'oh

2022-06-23 17:08 UTC, swysor commented on src/modules/cb_commland.erl
> +resource_exists() -> 'true'.
gotcha, thanks

2022-06-23 17:09 UTC, swysor commented on src/modules/cb_commland.erl
> +authorize_commland(_, ?HTTP_GET, ?COMPAT_NOUNS) ->
Do i need to worry about the path tokens here or is it ok for those to be _?

2022-06-23 17:14 UTC, swysor commented on src/modules/cb_commland.erl
> +authorize(Context, _) ->
Ok, makes sense. I wasn't quite clear if i have to implement the /1 version of these as well. do  i only need the arity 2 for these?

2022-06-28 15:17 UTC, swysor commented on src/modules/cb_commland.erl
> +authorize(Context, _) ->
removed those as well

2022-07-01 20:55 UTC, jamesaimonetti requested changes

2022-07-01 20:55 UTC, jamesaimonetti commented on priv/couchdb/schemas/system_config.crossbar.commland.json
> +            "default": "7f613340-1ebf-4710-ad57-fb4d3041af4c",
Do not set a default here. The `kapps_config:get` can set a default generated per cluster but it should definitely not be defined here.

2022-07-01 20:55 UTC, jamesaimonetti commented on priv/oas3/oas3-schemas.yml
> +'system_config.crossbar.commland':
what's the diff between crossbar.commland and commland system_config docs?

2022-07-01 20:55 UTC, jamesaimonetti commented on src/modules/cb_commland.erl
> +-define(BASE_SALT, kapps_config:get_ne_binary(?COMMLAND_CONFIG_CAT, <<"base_salt">>, <<"7f613340-1ebf-4710-ad57-fb4d3041af4c">>)).
Should look into a couple things:
1. generating a salt instead of hard-coding
2. can `kz_binary:rand_hex(16)` be enough?
3. some SUP methods in crossbar_maintenance to change the base salt

2022-07-01 20:55 UTC, jamesaimonetti commented on src/modules/cb_commland.erl
> +    kz_binary:md5(<<Version/binary, (?BASE_SALT)/binary>>).
I think you can just do `kz_binary:md5([Version, ?BASE_SALT])` and it should give you an MD5 hash

2022-07-05 14:38 UTC, swysor commented on src/modules/cb_commland.erl
> +-define(BASE_SALT, kapps_config:get_ne_binary(?COMMLAND_CONFIG_CAT, <<"base_salt">>, <<"7f613340-1ebf-4710-ad57-fb4d3041af4c">>)).
it has to be deterministic and is meant to obscure the version of the core it is querying. the core produces a hash that is also produced on the shipyard server serving  the packages. The URL here is the compatible path to upgrade commland.

2022-07-05 14:38 UTC, swysor commented on src/modules/cb_commland.erl
> +    kz_binary:md5(<<Version/binary, (?BASE_SALT)/binary>>).
righto, ill fix.

2022-07-05 14:40 UTC, swysor commented on priv/oas3/oas3-schemas.yml
> +'system_config.crossbar.commland':
oh i realized that i should be making a crossbar.commland not a commland system config doc since its parameters are only related to this api and i didn't want to step on future development with kazoo and commland. I can change it back to just commland if you would prefer.

2022-07-12 00:07 UTC, merged