coc-254-Refactor-5.1
2600hz/kazoo-crossbar pull request #342
Opened 2022-09-12 21:47 UTC by kdamas93

https://github.com/2600hz/kazoo-teletype/pull/52

2022-09-12 22:28 UTC, jamesaimonetti requested changes

2022-09-12 22:28 UTC, jamesaimonetti commented on src/modules/cb_conferences.erl
> +    ToFilterOut = [<<"undefinedconf">>],
If you only have the one value, hard-coded, you don't need to call lists:member below.
```erlang
[N || N <- ConferenceCallInNumbers, N =/= <<"undefinedconf">>].
```
Or `lists:delete(<<"undefinedconf">>, ConferenceCallInNumbers)` if only one instance of that value is present.

2022-09-12 22:32 UTC, icehess commented on src/modules/cb_conferences.erl
> +    ToFilterOut = [<<"undefinedconf">>],
Also move this logic to teletype itself. less code change and prs to merge.

2022-09-12 22:33 UTC, icehess commented on src/modules/cb_conferences.erl
> +    ToFilterOut = [<<"undefinedconf">>],
@jamesaimonetti is it safe to use `knm_converters:is_reconcilable/1` here? I don't think we ever use or even allow to use extension for conference?

2022-09-12 22:35 UTC, jamesaimonetti commented on src/modules/cb_conferences.erl
> +    ToFilterOut = [<<"undefinedconf">>],
There's no restriction on using extensions for a conference that I'm aware of.

2022-09-13 12:32 UTC, kdamas93 commented
Moving logic to teletype, less code change and prs to merge.

2022-09-13 12:38 UTC, kdamas93 commented
Moving logic to teletype, less code change and prs to merge.

2022-09-13 12:38 UTC, closed without merging