KZOO-335: add call limits schema
2600hz/kazoo-crossbar pull request #362
Opened 2022-10-21 05:06 UTC by harenson

Depends on: https://github.com/2600hz/kazoo-core/pull/512

Allows to set a maximum number of concurrent calls (limit) per endpoint (device/user) or account-wide. When building the endpoint, if limit is configured at endpoint level, it takes precedence over account's configuration in case limit was also configured account-wide.

2022-11-22 22:09 UTC, danielfinke approved these changes

2022-11-22 22:51 UTC, lazedo requested changes

2022-11-22 22:51 UTC, lazedo commented on priv/couchdb/schemas/call_limits.json
> +        }
lets add a `direction` property with enum inbound/outbound/both and default to `both`

2022-11-23 18:53 UTC, harenson commented on priv/couchdb/schemas/call_limits.json
> +        }
@lazedo should we stick with the existing `[inbound, outbound, any]` values for direction?

2022-11-23 18:59 UTC, lazedo commented on priv/couchdb/schemas/call_limits.json
> +        }
@harenson nm, lets leave it as-is

2022-11-23 19:01 UTC, harenson commented on priv/couchdb/schemas/call_limits.json
> +        }
@lazedo Ok, I will take care of the comments on the other related PRs, then. Thank you.

2022-11-23 19:24 UTC, harenson commented
_docs_ check is failing because it depends on https://github.com/2600hz/kazoo-core/pull/512 changes.

2022-11-25 10:46 UTC, lazedo approved these changes

2022-11-25 10:47 UTC, merged