KCRO-157 : Additional Restrictions on Voicemail Message API
2600hz/kazoo-crossbar pull request #368
Opened 2022-10-31 17:57 UTC by sanjeevie6353

KCRO-157 : Additional Restrictions on Voicemail Message API

Added system config flag that if enabled will cause the voicemail message API listing and retrieval to only succeed if the JWT belongs to an admin or if it belongs to a user that user is the owner of the voicemail box the message belongs to.

2022-10-31 20:19 UTC, jamesaimonetti requested changes

2022-10-31 20:19 UTC, jamesaimonetti commented on priv/couchdb/schemas/system_config.crossbar.json
> +            "description": "crossbar additional_restriction_on_request",
you can populate this with a proper description, please

2022-10-31 20:19 UTC, jamesaimonetti commented on src/cb_context.erl
> +    case kz_json:get_value(<<"owner_id">>, auth_doc(Context)) of
i think auth_user_id already does similar, no?

2022-10-31 20:19 UTC, jamesaimonetti commented on src/modules/cb_simple_authz.erl
> +    case kapps_config:get_is_true(?CONFIG_CAT, <<"additional_restriction_on_request">>, 'false') of
You define a macro then don't use it?

2022-10-31 20:19 UTC, jamesaimonetti commented on src/modules/cb_simple_authz.erl
> +        'false' -> 'true';
may as well just `not kapps_config:is_true(...)` vs a case, right?

2022-10-31 20:19 UTC, jamesaimonetti commented on src/modules/cb_simple_authz.erl
> +    request_allowed_for_user(cb_context:is_superduper_admin(AuthAccountId), Context).
Should just pass `cb_context:is_superduper_admin(Context)`; why use AuthAccountId instead?

2022-10-31 20:19 UTC, jamesaimonetti commented on src/modules/cb_simple_authz.erl
> +-spec validate_request_for_user(cb_context:context(), kz_term:ne_binary()) -> boolean().
This should probably not be defined here but in cb_vmboxes, in the authorize/N callbacks

2022-11-01 08:04 UTC, sanjeevie6353 commented on priv/couchdb/schemas/system_config.crossbar.json
> +            "description": "crossbar additional_restriction_on_request",
Changed the description of config parameter to **"crossbar allow request for only admins and owner of data"** on the following.
- swagger.json
- system_config.crossbar.json
- oas3-schemas.yml

Currently this is considered as a common config value. The aim is to be used for any other user level restrictions along with restrictions on VMBox message. Should this config only be related to VMBox messages?

2022-11-01 08:15 UTC, sanjeevie6353 commented on src/cb_context.erl
> +    case kz_json:get_value(<<"owner_id">>, auth_doc(Context)) of
Yes it seems to do the same. Changed the logic to use the auth_user_id() function and removed auth_doc_owner_id()

2022-11-01 08:26 UTC, sanjeevie6353 commented on src/modules/cb_simple_authz.erl
> +        'false' -> 'true';
Agreed on the change. Altered function to use not kapps_config:is_true(...) and removed the no_additional_restrictions() function

2022-11-01 08:27 UTC, sanjeevie6353 commented on src/modules/cb_simple_authz.erl
> +    case kapps_config:get_is_true(?CONFIG_CAT, <<"additional_restriction_on_request">>, 'false') of
This has been removed.

2022-11-01 08:35 UTC, sanjeevie6353 commented on src/modules/cb_simple_authz.erl
> +    request_allowed_for_user(cb_context:is_superduper_admin(AuthAccountId), Context).
Used an already available function at  `**authorize(Context, Verb, _Nouns)**`  function (in cb_simple_authz.erl). I've changed my function to use `cb_context:is_superduper_admin(Context)`.

Shall I change other places that use AuthAccountId?

2022-11-01 14:16 UTC, sanjeevie6353 commented on src/modules/cb_simple_authz.erl
> +-spec validate_request_for_user(cb_context:context(), kz_term:ne_binary()) -> boolean().
The intention of defining these functions in the cb_simple_authz.erl was to allow new api urls to be defined in new clauses. 

This will allow to restrict url access on requests other than vm_box_messages. 

If I'm to put this inside cb_vmboxes.erl, it will restrict this functionality only to vmboxes. So, Is it ok to keep the current implementation intact?

2022-11-01 15:05 UTC, jamesaimonetti commented on src/modules/cb_simple_authz.erl
> +-spec validate_request_for_user(cb_context:context(), kz_term:ne_binary()) -> boolean().
no, as we have an `authorize` available for each endpoint that needs to define custom rules. Let's keep the `simple` in `cb_simple_authz`.

2022-11-01 15:06 UTC, jamesaimonetti commented on src/modules/cb_simple_authz.erl
> +    request_allowed_for_user(cb_context:is_superduper_admin(AuthAccountId), Context).
no, only places you've touched. Will have to evaluate other instances to find out why they are as they are. Thanks for looking into it

2022-11-01 16:58 UTC, sanjeevie6353 commented on src/modules/cb_simple_authz.erl
> +-spec validate_request_for_user(cb_context:context(), kz_term:ne_binary()) -> boolean().
Did the change to move functionality to cb_vmboxes

2022-11-01 23:29 UTC, jamesaimonetti requested changes

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_token_restrictions.erl
> +    case props:get_value(<<"vmboxes">>, cb_context:req_nouns(Context)) of
This change is unnecessary. cb_vmboxes:authorize should return true/false and things should just work. This module has nothing to do with vmboxes and should have no logic associated with it. I think the vmboxes module's change should be sufficient for whether to allow the request or not.

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +    authorize(cb_context:is_superduper_admin(Context), Context).
As a general request, keep argument order when calling sub-functions. There's a minor speed improvement with maintaining order compared to moving their positions around.
So `authorize(Context, cb_context:is_superduper_admin(Context)).`

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +    authorize(cb_context:is_superduper_admin(Context), Context).
And it just bugs me lol

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +            lager:debug("validate request for user failed for Owner: ~p", [OwnerId]),
I would say something more like "vmbox ~s has no owner, auth user ~s cannot access this box", [VMBoxId, AuthUserId]

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +    OwnerId = cb_context:auth_user_id(Context),
This should be `AuthUserId`

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +        OwnerId -> 'true';
This should be `AuthUserId` as well

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +            lager:debug("validate request for user failed - Requester is not the Owner: ~p", [_OtherOwnerId]),
"access to vmbox ~s for auth user ~s denied, box is owned by ~s", [VMBoxId, AuthUserId, _OwnerId]

2022-11-01 23:29 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +                    validate_request_for_user(Context, cb_context:path_tokens(Context))
Use `cb_context:req_nouns(Context)` instead, you'll get the list of endpoints (in reverse order) plus their arguments.

`validate_request_for_user` then becomes:
```
validate_request_for_user(Context, [{<<"vmboxes">>, [VMBoxId | _ ]}, {<<"accounts">>, [AccountId]}]) ->
    ...
```
Basically any API under vmboxes, with a Box ID, should be checked for ownership (so /vmboxes/ID, /vmboxes/ID/messages and /vmboxes/ID/messages/MSG_ID)

2022-11-02 12:36 UTC, sanjeevie6353 commented on src/modules/cb_vmboxes.erl
> +    authorize(cb_context:is_superduper_admin(Context), Context).
I did not know that tbh... I'll take a note on this... Thank you...

This change has been done..

2022-11-02 12:43 UTC, sanjeevie6353 commented on src/modules/cb_vmboxes.erl
> +    OwnerId = cb_context:auth_user_id(Context),
Changed this to `AuthUserId`

2022-11-02 12:43 UTC, sanjeevie6353 commented on src/modules/cb_vmboxes.erl
> +        OwnerId -> 'true';
Changed this to AuthUserId

2022-11-02 12:45 UTC, sanjeevie6353 commented on src/modules/cb_vmboxes.erl
> +            lager:debug("validate request for user failed - Requester is not the Owner: ~p", [_OtherOwnerId]),
Changed the log

2022-11-02 12:46 UTC, sanjeevie6353 commented on src/modules/cb_vmboxes.erl
> +            lager:debug("validate request for user failed for Owner: ~p", [OwnerId]),
Changed the log

2022-11-02 16:33 UTC, sanjeevie6353 commented on src/modules/cb_token_restrictions.erl
> +    case props:get_value(<<"vmboxes">>, cb_context:req_nouns(Context)) of
This logic has been removed.

2022-11-02 16:34 UTC, sanjeevie6353 commented on src/modules/cb_vmboxes.erl
> +                    validate_request_for_user(Context, cb_context:path_tokens(Context))
This has been fixed.

2022-11-08 04:25 UTC, jamesaimonetti commented
Tests in https://github.com/2600hz/kazoo-properly/pull/103

2022-11-08 19:37 UTC, merged