kcro-148-CommlandSelectorApi-master
2600hz/kazoo-crossbar pull request #374
Opened 2022-11-09 17:25 UTC by kdamas93

The purpose of this API is to replicate the behavior of the **apps_store** API with the following differences:

-It will be possible to perform actions on the following resources through the **cb_application** endpoint
-application document which includes screenshots, icons, entitlement, and blocklist among others.

The creation and management of permissions for this will be in each account, unlike the current scheme that was only allowed in the master account.

This API will also allow handling different types of applications, for example, **commland_ui** and **monster_ui** , a field has been added which specifies the type of application that has been created. With this it is hoped to be able to have controlled and grouped the different applications that may arise within their category.

It has created its own module in core to execute actions from the console, the module is called **kazoo_ui_apps_maintenance**, and the related pr is https://github.com/2600hz/kazoo-core/pull/524, it has been developed based on **kazoo_documents_maintenance**, keeping the functionality that exists for monster-ui applications that follow the current architecture

The API contains its own schema, views and functions

2022-11-17 19:23 UTC, icehess commented
@kdamas93 I don't understand the need for new functions. These functions should be same for both MUI, commland or any other app type in the future.

You can simply repurpose the current functions or enhance them to get what you want.

Also I don't see anything about `application_type` here.

Another thing, if you look `init_apps` is actually moved to `kazoo_document_maintenance`. This the place you have to write the `init_applications`. This function must be in core, since kazoo_appex also depends on it.

2022-11-17 19:40 UTC, kdamas93 commented
@icehess 
What functions are you referring to?
I tried to adapt and reuse as much as possible, I would appreciate it if you could tell me what they are:

Regarding the logic related to `application_type`, it is contained in `cb_applications`:

I will start working on the observation about `init_apps`/`init_applications`

2023-01-10 19:20 UTC, icehess commented
@kdamas93 @ashleyvernon Here is the summary of our meeting:

1. create JSON schema for both `application_blocklist` and `application_entitlement` here,
2. run `scripts/generate-kzd-builders.escript` to generate the `kzd` accessor for `application_blocklist` and `application_entitlement` and `application`, copy them to https://github.com/2600hz/kazoo-core/pull/524
3. Do not use a static id for block list and entitlement. Let doc id be random as usual (you don't need to do anything). instead save app block or app entitlement PER app as a separate doc. store the app id in the doc
4. create a view to return application block list and entitlement per app type and app id

Second part is to document everything, (you can put the these internal docs inside `kazoo_document`, it doesn't matter where you as long as you properly document this stuff):
1. Properly document how the new application is working, what is the difference between application api and apps_store api. You mention something you copied the existing cb_apps_store code and adjusted to what you want it to do, DOCUMENT your change then.
2. same thing for init_apps and init_applications, document how they are different from each other.

If you document this properly we can review the change and see if the code is up to spec and make decision better.

2023-01-19 20:05 UTC, icehess requested changes

2023-01-19 20:05 UTC, icehess commented on priv/couchdb/schemas/application_blocklist.json
> +        },
these are private fields, and are automatically is added if you use crossbar_docs to save docs.
Do not add these fields to schema

2023-01-19 20:05 UTC, icehess commented on priv/couchdb/schemas/application_blocklist.json
> +        "application_type": {
rename to `type` is simpler and no need to say application again

2023-01-19 20:05 UTC, icehess commented on priv/couchdb/schemas/application_blocklist.json
> +        "name_application": {
rename to `name` is simpler and no need to say application again

2023-01-19 20:15 UTC, icehess requested changes

2023-01-19 20:15 UTC, icehess commented on priv/couchdb/schemas/application_entitlement.json
> +        },
same thing, don't add private keys to schema

2023-01-19 20:15 UTC, icehess commented on priv/couchdb/schemas/application_entitlement.json
> +        "application_type": {
drop application, type is enough

2023-01-19 20:15 UTC, icehess commented on priv/couchdb/schemas/application_entitlement.json
> +        "name_application": {
drop application, name is enough

2023-01-19 20:15 UTC, icehess commented on priv/couchdb/schemas/application_entitlement.json
> +        },
So we want to make the entitlement to only allow setting to all users, or admins only or a list of individual users.
When the entitlement type is specific, we need another field to track the list of specific user ids.

To make this work properly we also want to make sure this entitlement type is mutually exclusive, meaning you are either to allow all/admins or allow a specific list of user ids which in turn needs and extra property call `users` to hold the list of user ids.

For achieving this mutually exclusive JSON schema provides `oneOf`, this forces only usage of only one listed schema:

```
        "entitlement": {
            "oneOf": [
                {
                    "properties": {
                        "type": {
                            "description": "Type of entitlement granted or users with the entitlement",
                            "enum": [
                                "all",
                                "admins"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "type"
                    ]
                },
                {
                    "properties": {
                        "type": {
                            "description": "Type of entitlement granted or users with the entitlement",
                            "enum": [
                                "specific"
                            ],
                            "type": "string"
                        },
                        "users": {
                            "default": [],
                            "description": "Type of entitlement granted or users with the entitlement",
                            "items": {
                                "type": "string"
                            },
                            "type": "array"
                        }
                    },
                    "required": [
                        "type"
                    ]
                }
            ]
        },
```

2023-01-19 20:16 UTC, k-anderson commented on priv/couchdb/schemas/application.json
> +        "allowed_users": {
This is property of the entitlement not the application meta-data so should be removed.

2023-01-19 20:16 UTC, k-anderson commented on priv/couchdb/schemas/application.json
> +        "users": {
This is property of the entitlement not the application meta-data so should be removed.

2023-01-19 20:31 UTC, icehess commented
Also as suggesting, if you could implement test for cb_apps_store and your new cb_application module that would be nice way to make sure we all previous features/functionalities are still present in the new API

2023-04-18 18:33 UTC, icehess requested changes

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +    _ = crossbar_bindings:bind(<<"*.authorize">>, ?MODULE, 'authorize'),
Remove these and their functions, these are all optional. and here you are not doing anything you can remove them then.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +    _ = crossbar_bindings:bind(<<"*.content_types_provided.applications">>, ?MODULE, 'content_types_provided'),
Bind for content_type_accepted too and implement it. you can copy paste it from cb_apps_store. especially the part about how it handles the icons and screenshots.

Also lok for how cb_apps_Store is implementing the icon/screenshots uploads on post/put.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +        , authenticate/1, authenticate/2, authenticate/3, authenticate/4, authenticate/5
a minor cosmetic issue, remove the space after first comma.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +authenticate_nouns(?HTTP_DELETE, [{<<"applications">>,[_AppType, _AppId, ?SCREENSHOT, _Number]}]) ->'true';
Is this a dev time test thing? why authenticate the request for every API that this module provide?

Maximum thing we want to allow to open public access are these:

```erlang
authenticate_nouns(?HTTP_GET, [{<<"applications">>,[_AppType, _AppId, ?ICON]}]) ->'true';
authenticate_nouns(?HTTP_GET, [{<<"applications">>,[_AppType, _AppId, ?SCREENSHOT, _Number]}]) ->'true';
```

I can debate that we don't even need these. but for now let's do what exactly apps_store is doing.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +    case cb_context:is_account_admin(Context) of
If you can refactor this such as extract common logic `when`: reseller, master, admin to go over a common function and do pattern match on nouns and method and calls those `when` functions this makes this authorize functions more readable.

Currently it is really hard to follow :)

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +    end;
This logic should be move to `cb_apps_util:allowed_applications(AppType)`, `cb_apps_util:allowed_applications(AppType, AccountId)`, and `cb_apps_util:allowed_applications(AppType, AccountId, UserId)`.

Same for next clause and anywhere in the code. The propose of this module should be only providing the API stuff (authorize, validate, basic CRUD - create, read, update, delete stuff,...) and not the business logic (how to list apps or if the account/user is allowed to access which app,...).

I suggest take a look at how `cb_apps_util:allowed_apps` is implemented and follow the same pattern. You can enhance the code but I like to see it fetches all apps from master, reseller and fold over some routines to check the app permissions, block and etc...

I can debate that we can even move this business logic back to the core. Not sure we need logic anywhere else, but just in case. Any thoughts?

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +filter_entitlement_by_user ([], Results, _UserId, _IsAdmin) ->
move this `cb_apps_util` we don't want this logic to be here.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +            AccountId = cb_context:account_id(Context),
Did you meant `cb_context:auth_account_id/1`?

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +                    Doc = kz_json:set_values(Values, kzd_application_blocklist:new()),
Use module kzd_application_entitlement functions and kz_doc:setter/2 function to manipulate the doc.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +validate_merged_applications(Context, ApplicationType, ?HTTP_GET) ->
move this `cb_apps_util` we don't want this logic to be here.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +                    Values = [{<<"type">>, ApplicationType}
In general, manipulating the doc fields directly in highly discouraged. Please use standard `kz_doc` module to access common pvt fields, and use you document `kzd` module to get and set fields. That is why we created `kzd` modules in the first place to avoid these direct JObj manipulations.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +merge_application_entitlements(_Context, [], Results) -> Results;
move this `cb_apps_util` we don't want this logic to be here.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +services_apps([], _Services, Results) -> Results;
move this `cb_apps_util` we don't want this logic to be here.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +blocklist_apps([], _Blocklist, Results) -> Results;
move this `cb_apps_util` we don't want this logic to be here.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +                    Values = [{<<"name">>, ApplicationName}
use kzd modules

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +            Values = [{<<"name">>, ApplicationName}
Not gonna repeat this for the rest of code, don't manipulate JObj directly use `kzd` modules.

this is not a good place to say this, as this code can be completely done using `crossbar_doc:load_merge` and we don't ned to do anything here, follow the [`applications/skels/src/intergations/cb_crud.erl`](https://github.com/2600hz/kazoo-skel/blob/master/src/integration/cb_crud.erl) to see how this usually should be implemented.

But in general we don't manipulate the doc fields directly and we use kzd and setters. like this:
```erlang
Setters = [{fun kzd_application_entitlement:set_name/2, AppName}
          ,{fun kzd_application_entitlement:set_type/2, AppType}
          ,{fun kz_doc:set_type/2, kzd_application_entitlement:type()}
          ],
kz_doc:setters(Doc, Setters).
```

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +                              );
You can return Context, it already have the proper error set.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +validate_application_entitlement(Context, ApplicationType, AppId, ?HTTP_PATCH) ->
Usually in Crossbar we impelement a common function to read the a signle doc. like here `load_application_entitlement`

Then in validate base on HTTP method/verb, we either load_application_entitlement call for GET/DELETE.

For PUT/POST/PATCH we validate the request first, meaning we validate the payload using schema, if PATCH we crossbar_doc:patch_and_validate, and then for POST after schema validation we do load_merge. All POST/PATCH/PUT wil call validate_request with the Id of doc, in case of PUT it is undefined which set the pvt using kzd_module or something or kz_doc directly. You can look at all other cb module to see how this usually is done. See and example here: https://github.com/2600hz/kazoo-skel/blob/master/src/integration/cb_crud.erl

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +    ApplicationContext = crossbar_doc:load(AppId, Context),
See above comments, we do crossbar_doc:patch_and_validate which loads the curernt doc and merge with the req data and performs schema validation.

2023-04-18 18:33 UTC, icehess commented on src/modules/cb_applications.erl
> +            cb_context:setters(ApplicationContext
Like comment above please don't reset error, it ia relady set bu load function.

2023-04-18 20:51 UTC, icehess requested changes

2023-04-18 20:51 UTC, icehess commented on src/modules/cb_applications.erl
> +    content_types_accepted(Context, ?ICON, cb_context:req_verb(Context)).
Also implement the `content_types_accepted` for icon and `sceenshots, number` and only allow image file formats like `?IMAGE_CONTENT_TYPES`

https://github.com/2600hz/kazoo-crossbar/blob/master/src/modules/cb_apps_store.erl#L169-L184

Don't forget to bind to it in init function.

2023-06-15 20:51 UTC, jamesaimonetti requested changes
Things to review and fix, see core PR review as well

2023-06-15 20:51 UTC, jamesaimonetti commented on src/crossbar_maintenance.erl
> +%% @doc U.
What is this comment for?

2023-06-15 20:51 UTC, jamesaimonetti commented on src/modules/cb_applications.erl
> +        , authenticate/1
please follow project formatting standards and remove the space between the comma and function/arity

2023-06-15 20:51 UTC, jamesaimonetti commented on doc/ref/applications.md
> +# Applications
This ref doc needs to be migrated to `crossbar/doc/applications/md` and be filled in appropriately.

2023-06-15 20:51 UTC, jamesaimonetti commented on src/cb_apps_util.erl
> +                   'include_docs'],
drop end of list char `]` to newline
comma-first for the list elements in here:

```erlang
[{startkey, [..]}
 ,{endkey, [...]}
 ,include_docs
],
```

2023-06-15 20:51 UTC, jamesaimonetti commented on src/cb_apps_util.erl
> +find_application_attachment(_, _, []) ->
This function does not appear to ever have a chance to be called with `(JObj, AttachmentName, [])` as args so this clause seems unneeded.

2023-06-15 20:51 UTC, jamesaimonetti commented on src/cb_apps_util.erl
> +find_application_attachment(_, _, []) ->
A question though: this function seems identical to `find_attachment`; what's the difference here?

2023-06-15 20:51 UTC, jamesaimonetti commented on src/modules/cb_applications.erl
> +    NewObj = cb_context:doc(crossbar_doc:load(AppId,Context), ?TYPE_CHECK_OPTION(kzd_application:type())),
cb_context:doc/2 does not exist. run `make xref` to show you all the places where the code makes bad function calls.

2023-06-15 20:51 UTC, jamesaimonetti commented on src/modules/cb_applications.erl
> +    case cb_context:account_id(Context) of
cb_context:account_id does not return a tuple so why pattern match here for it?

2023-06-15 20:51 UTC, jamesaimonetti commented on src/modules/cb_applications.erl
> +    case cb_context:account_id(Context) of
This whole function seems unnecessary

2023-06-15 20:51 UTC, jamesaimonetti commented on src/modules/cb_applications.erl
> +app_attachment_id({<<"application">>, ?SCREENSHOT}, Doc, _Language) ->
This clause does not look reachable. I don't see anywhere it is called with this first arg's tuple().

2023-06-27 23:33 UTC, icehess commented
Required PRs:

- https://github.com/2600hz/kazoo-crossbar/pull/374
- https://github.com/2600hz/kazoo-core/pull/524
- https://github.com/2600hz/kazoo-properly/pull/156
- https://github.com/2600hz/kazoo-ast/pull/42

2023-07-12 15:46 UTC, merged