KCAL-45 Add aliases to the voicemail box
2600hz/kazoo-crossbar pull request #381
Opened 2022-11-15 12:09 UTC by nkarunarathne

Previously the voicemail box had only a voicemail box number for box identification. It was requested add new aliases so that the voicemail box can be looked up using either the voicemail number or aliases.

The new 'aliases' parameter is a list of strings that can be used to identify a voicemail box uniquely. Each voicemail box number and/or aliases are always unique in the account.

Also, The voicemail aliases can be used as transfer targets. The voicemail aliases can be used when calling to check voicemail where the voicemail box number is asked for.

The Code Level Change

Edited the existing listing_by_mailbox view so that it would check both voicemail box IDs and aliases when doing the lookups.
Check the uniqueness of both voicemail box IDs and aliases when receiving API requests.
The voicemail box lookup was using an integer box number, changed it to binary. 

Changes are in
crossbar, callflow, core

2022-11-18 17:48 UTC, icehess requested changes
You also need to modify these crossbar views, search for vmbox cases and add aliases to mailbox if it needs:

* `core/kazoo_couch/priv/couchdb/views/account-crossbar_listings.json` in kazoo-core
* `applications/locations/priv/couchdb/views/account-locations.json` in kazoo-locations repo

2022-11-18 17:48 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    | kz_json:get_value(<<"aliases">>, cb_context:req_data(Context), [])].
```suggestion
    [kzd_vmboxes:mailbox(cb_context:req_data(Context))
     | kzd_vmboxes:aliases(cb_context:req_data(Context), [])
    ].
```

2022-11-18 17:48 UTC, icehess commented on src/modules/cb_vmboxes.erl
>      end.
We don't need try/cactch anymore, so you can get ride of it.
Also handle empty case!

```
    case get_aliases_and_mailbox(Context) of
        [] ->
            lager:debug("no mailbox number or aliases"),
            'false';
        BoxIdentities ->
            check_uniqueness(VMBoxId, Context, BoxIdentities)
    end.
```

2022-11-22 22:42 UTC, icehess requested changes

2022-11-22 22:42 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    ].
fmt is erroring because we prefer to have new line  character at the end of file, just hit enter after `.` here will fix it.

2022-11-22 22:42 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    | kzd_vmboxes:aliases(cb_context:req_data(Context), [])
I could be wrong but i think our formatter likes a space before `|`:

```suggestion
    [kzd_vmboxes:mailbox(cb_context:req_data(Context))
     | kzd_vmboxes:aliases(cb_context:req_data(Context), [])
```

2022-11-22 22:42 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +            (length(BoxIdentities) =:= length(props:unique(BoxIdentities)));
We usually drop `and/or` or `andalso/orelse` to a new line followed by right hand side, also no need for parentheses:

```suggestion
            lists:all(fun(VMBox) -> VMBoxId =:= kz_doc:id(VMBox) end, Boxes)
                andalso length(BoxIdentities) =:= length(props:unique(BoxIdentities));
```

2022-11-23 12:47 UTC, nkarunarathne commented on src/modules/cb_vmboxes.erl
> +    | kzd_vmboxes:aliases(cb_context:req_data(Context), [])
There is no space there, it is usually like this 

https://github.com/2600hz/kazoo-ast/blob/2af19c3f246efe3ae78069821149c3c8d793384c/src/cb_api_endpoints.erl#L909-L912

2022-11-23 18:04 UTC, icehess requested changes
lgtm, just some small changes.

2022-11-23 18:04 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    ].
Let's do this instead:
```suggestion
    lists:usort(
      [BoxIdentity
       || BoxIdentity <- [kzd_vmboxes:mailbox(cb_context:req_data(Context))
                         | kzd_vmboxes:aliases(cb_context:req_data(Context), [])
                         ],
          kz_term:is_not_empty(BoxIdentity)
      ]
    ].

```

2022-11-23 18:04 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +                andalso length(BoxIdentities) =:= length(props:unique(BoxIdentities));
hmm, I'm not following what this line is checking exactly?

2022-11-23 18:04 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +        ['undefined'] ->
With the change suggested for `get_aliases_and_mailbox` you can safely check for empty list here.

2022-11-23 18:04 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +-spec check_uniqueness(kz_term:api_binary(), cb_context:context(), kz_term:api_list()) -> boolean().
```suggestion
-spec check_uniqueness(kz_term:api_binary(), cb_context:context(), kz_term:ne_binaries()) -> boolean().
```

2022-11-23 19:09 UTC, nkarunarathne commented on src/modules/cb_vmboxes.erl
> +    ].
Why do we need to sort this, order dose not matter here I think.

2022-11-23 19:12 UTC, nkarunarathne commented on src/modules/cb_vmboxes.erl
> +                andalso length(BoxIdentities) =:= length(props:unique(BoxIdentities));
This check will prevent adding the same VM box number or alias to other boxes as well as, the same VM box number to the same box aliases list as well.

2022-11-23 19:14 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    ].
`usort` is sort and **unique**, so you don't need to unique it in after you fetch the view.

2022-11-23 19:17 UTC, nkarunarathne commented on src/modules/cb_vmboxes.erl
> +    ].
got it

2022-11-23 19:22 UTC, nkarunarathne commented on src/modules/cb_vmboxes.erl
> +    ].
But if I do that It will break the logic in line 1303.

2022-11-23 21:11 UTC, danielfinke commented on src/modules/cb_vmboxes.erl
> +        kz_term:is_not_empty(BoxIdentity)
If you move the check for uniqueness to after the schema validation, you won't need to check if the identities are empty (since the schema is checking `"minLength": 1` for each alias

2022-11-28 20:11 UTC, icehess requested changes

2022-11-28 20:11 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    case check_uniqueness(VMBoxId, ValidatedContext) of
Now since you are checking schema first, then before checking the uniqueness you need to check if `validateContext` resp_status is `success` then continue with uniqueness.

Something like this would suffice:
```
    case cb_context:resp_status(ValidatedContext) of
        'success' ->
                case check_uniqueness(VMBoxId, ValidatedContext) of
....
....
        _SchemaInvalid ->
            ValidateContext
    end.
```

Other option is to move check uniqueness to `OnSuccess` function of validate schema. but you need to maintain (or actually move) the check db name concept of `validate_unique_vmbox` to the new function.

2022-11-28 23:09 UTC, jamesaimonetti commented on src/modules/cb_vmboxes.erl
> +    case check_uniqueness(VMBoxId, ValidatedContext) of
Interestingly, the properly check I added failed when trying to create a second box with the same "mailbox" as first created, suggesting the uniqueness check, as-is, isn't working as expected. See https://app.circleci.com/pipelines/github/2600hz/kazoo-properly/571/workflows/e7e6a9da-3424-4b14-991f-25b34e45b889/jobs/4174

2022-11-29 17:41 UTC, merged

2022-11-29 18:20 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    case check_uniqueness(VMBoxId, ValidatedContext) of
lol, probably it couldn't get mailbox properly because of invalid schema?