KZOO-323: add support for user-defined metadata on call recordings
2600hz/kazoo-crossbar pull request #386
Opened 2022-11-22 17:36 UTC by danielfinke

- `user_metadata` can be modified with a POST to `/recordings`
- attempt to update metadata in storage backends before saving in
  crossbar
- doc usage of metadata for S3 object tag-set when S3 attachment handler
  is configured in storage plan

kazoo5 PR: https://github.com/2600hz/kazoo5/pull/87
kazoo-core PR: https://github.com/2600hz/kazoo-core/pull/536
kazoo-core PR 2: https://github.com/2600hz/kazoo-core/pull/550
kazoo-media-mgr PR: https://github.com/2600hz/kazoo-media-mgr/pull/29

2022-11-22 18:17 UTC, icehess requested changes

2022-11-22 18:17 UTC, icehess commented on src/modules/cb_recordings.erl
> +    case kz_json:is_json_object(kzd_call_recordings:key_user_metadata(), Diff) of
How about using the accessor directly?

```suggestion
    case kz_json:is_json_object(kzd_call_recordings:user_metadata(Diff)) of
```

2022-12-08 23:28 UTC, jamesaimonetti commented on src/modules/cb_recordings.erl
> +validate_only_writable_props_changed(Context) ->
I think once you go PATCH, just verify that only write-able fields are included in the request data. If any field is not write-able, schema error returned.

Then you don't have to do this funky diff dance below.

2022-12-09 21:26 UTC, danielfinke commented
@jamesaimonetti ready for re-review and also opened up this one -> https://github.com/2600hz/kazoo-core/pull/550

2022-12-09 22:52 UTC, jamesaimonetti commented on src/modules/cb_recordings.erl
> +                                    ,fun validate_only_writable_props_included/1
I think you want to validate the req data before you call `crossbar_doc:patch_and_validate/4` above, since we would want to error the request is a non-writeable field is present in the request.

As-is, you fetch the doc, merge the request, validate the merged doc, then check the request for bad fields - a lot of unnecessary work

2022-12-12 16:29 UTC, danielfinke commented on src/modules/cb_recordings.erl
> +                                    ,fun validate_only_writable_props_included/1
Good point, I've switched the order of those validations

2022-12-12 18:18 UTC, merged