KCRO-167: Streamchat Kazoo integration not updating existing users
2600hz/kazoo-crossbar pull request #387
Opened 2022-11-23 20:17 UTC by kdamas93

2022-11-23 22:24 UTC, icehess requested changes
Some code change suggestions.

Also fyi alternative approach is to there separate functions one each to check if getstream role, username and name are matching with request.

2022-11-23 22:24 UTC, icehess commented on src/modules/cb_getstream.erl
> +    NameGetstream = kz_json:get_ne_value(<<"name">>, User),
It is better to use `kz_json:get_ne_binary_value/2` so we know they should be string.

2022-11-23 22:24 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Role = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData),
Just checking is this correct? how can we assume user_id can be priv_level?

2022-11-23 22:24 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Role = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData),
Also for this and the lines below it, is the order of keys correct? Isn't better to first check for `username` if it is missing then use user_id?

2022-11-23 22:24 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Name = <<FirstName/binary, LastName/binary>>,
Just checking do we expect getstream also concat first and last names without any space between them?

2022-11-23 23:21 UTC, jamesaimonetti commented on src/modules/cb_getstream.erl
> +               [{<<"users">>, [[{<<"id">>, UserId}
It can be difficult to parse large bodies like this and make changes at the right level of the object.

I would suggest breaking the pieces out (like the `set` value should just be an object created before Params and included as `{<<"set">>, SetParams}`

2022-11-23 23:23 UTC, jamesaimonetti commented on src/modules/cb_getstream.erl
> +        {'ok', 200, _RespHeaders, RespBody} ->
If you aren't using a value, or only using it for logging purposes, prefix with the variable with `_`.

2022-11-24 00:20 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    NameGetstream = kz_json:get_ne_value(<<"name">>, User),
changes added : 
```
 RoleGetstream = kz_json:get_ne_binary_value(<<"role">>, User),
 UsernameGetstream =kz_json:get_ne_binary_value(<<"username">>, User),
 NameGetstream = kz_json:get_ne_binary_value(<<"name">>, User),
```

2022-11-24 00:28 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    Role = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData),
> Just checking is this correct? how can we assume user_id can be priv_level?

I do not fully understand the question, it was defined as follows at the beginning, in which case the getstream section does not exist, it will take the kazoo one, which is the priv_level that defines the role in kazoo, be it `admin` or `user`

2022-11-24 00:42 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    Role = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData),
> Also for this and the lines below it, is the order of keys correct? Isn't better to first check for `username` if it is missing then use user_id?

Actually the purpose is to compare if any property has changed to make the `patch`, therefore in my opinion I consider that the order does not matter

2022-11-24 00:43 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    Name = <<FirstName/binary, LastName/binary>>,
> Just checking do we expect getstream also concat first and last names without any space between them?

Yes, since that was the way we created it, I attach a code snippet

2022-11-24 00:44 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    Name = <<FirstName/binary, LastName/binary>>,
` 

    Headers = create_headers(TokenHeader),

    FirstName = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>],<<"first_name">>],UserData),
    LastName = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>],<<"last_name">>],UserData),

    Body = kz_json:from_list(
             [{<<"id">>, UserId},
              {<<"teams">>, [cb_context:account_id(Context)]},
              {<<"username">>, kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"username">>], UserData)},
              {<<"name">>, <<FirstName/binary, LastName/binary>>},
              {<<"role">>, kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData)}
             ]),
`

2022-11-24 00:46 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +    Name = <<FirstName/binary, LastName/binary>>,
This is located in the function `create_getstream_user`

2022-11-24 19:23 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +               [{<<"users">>, [[{<<"id">>, UserId}
Changes added: 
```
UserProperties = {<<"set">>, [{<<"username">>, kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"username">>], UserData)}
                                 ,{<<"name">>, <<FirstName/binary, LastName/binary>>}
                                 ,{<<"role">>, kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData)}
                                 ]
                     },
```

```
Params = kz_json:from_list_recursive(
               [{<<"users">>, [[{<<"id">>, UserId}
                               ,UserProperties
                               ]
                              ]
                }
               ]
              ),
```

2022-11-24 19:28 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +        {'ok', 200, _RespHeaders, RespBody} ->
```
case kz_http:patch(URL, Headers, JsParams) of
        {'ok', 200, _RespHeaders, _RespBody} ->
            lager:debug("user updated: ~p",[_RespBody]),
            'true';
        {'error', _E} ->
            lager:debug("failed: ~p", [_E]),
            'false'
    end
```

2022-11-28 19:58 UTC, icehess requested changes

2022-11-28 19:58 UTC, icehess commented on src/modules/cb_getstream.erl
> +               [{<<"users">>, [[{<<"id">>, UserId}
@kdamas93 Try this:

```
    Usernmae = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"username">>], UserData),
    UserRole = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData),
    UserProperties = kz_json:from_list(
                       [{<<"id">>, UserId}
                       ,{<<"set">>
                        ,kz_json:from_list(
                           [{<<"username">>, Username}
                           ,{<<"name">>, <<FirstName/binary, LastName/binary>>}
                           ,{<<"role">>, UserRole}
                           ]
                          )
                        }
                       ]
                      ),

    Params = kz_json:from_list([{<<"users">>, [UserProperties]}]),
```

2022-11-28 19:58 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Role = kz_json:get_first_defined([[<<"getstream">>, <<"user_id">>], <<"priv_level">>], UserData),
You are using get_first_defined, what if `[getstream, user-id]` is not changed but the user's priv_level changed on kazoo side? So the order is matter!

Then, first of all, you are using `[getstream, user_id]` for everything from username, to priv_level to name and etc.

I don't know what is `[getstream, user-id]` or where it came from or is this something that user can set by themselves or it is changeable by user at all.  I don 't even know even what getstream is. But for me the logic of using the same key for everything seems wrong.

What if there is indeed `[getstream, user-id]` key define in the user doc? then we are using the same key for everything, such as name, username and role.

If you want to get the role, then get it from `priv_level`. we always have priv_level, first_name and last_name and username define in user doc.

If you do fist get getstream user_id then fall back to to other keys, then ahen we figureout that user_id in the future we never use the other key. Like when you are calling update getstream it always use user_id for everything which is wrong and can replace the correct value of the role for example when the user first initially create in getstream.

Also imo we should NOT allow allow changing the getstream user_id. the proper way is to save it as a private key and leak the value as readonly to crossbar response.

I know this is not what you're trying to fix here, but the logic here seems wrong.

In other hand, if the indent here is to check if any of those fields are changed, then instead of doing this here you can simply create a list of all key paths that you want to check and fold over it and compare original and new one to see if they changed.

2022-11-29 16:30 UTC, kdamas93 commented
You are using get_first_defined, what if [getstream, user-id] is not changed but the user's priv_level changed on kazoo side? So the order is matter!

**KD**: Order changed.
`UserRole = kz_json:get_first_defined([<<"priv_level">>, [<<"getstream">>, <<"role">>]], UserData),`

Then, first of all, you are using [getstream, user_id] for everything from username, to priv_level to name and etc.

I don't know what is [getstream, user-id] or where it came from or is this something that user can set by themselves or it is changeable by user at all. I don 't even know even what getstream is. But for me the logic of using the same key for everything seems wrong.

**KD:** Observation understood:
Change made

```
FirstName = kz_json:get_first_defined([[<<"getstream">>, <<"first_name">>],<<"first_name">>],UserData),
LastName = kz_json:get_first_defined([[<<"getstream">>, <<"last_name">>],<<"last_name">>],UserData),

Username = kz_json:get_first_defined([[<<"getstream">>, <<"username">>], <<"username">>], UserData),
```


What if there is indeed [getstream, user-id] key define in the user doc? then we are using the same key for everything, such as name, username and role.
**KD :** Changes made :
`UserId = kz_json:get_value(<<"_id">>, UserData),`


If you want to get the role, then get it from priv_level. we always have priv_level, first_name and last_name and username define in user doc.

If you do fist get getstream user_id then fall back to to other keys, then ahen we figureout that user_id in the future we never use the other key. Like when you are calling update getstream it always use user_id for everything which is wrong and can replace the correct value of the role for example when the user first initially create in getstream.

Also imo we should NOT allow allow changing the getstream user_id. the proper way is to save it as a private key and leak the value as readonly to crossbar response.

I know this is not what you're trying to fix here, but the logic here seems wrong.

In other hand, if the indent here is to check if any of those fields are changed, then instead of doing this here you can simply create a list of all key paths that you want to check and fold over it and compare original and new one to see if they changed.
**KD:**
@icehess  I hadn't realized that I was using the **[getstream, user_id]** for all the keys
The requested changes have been made, I appreciate your patience and explanation, let me know if there is anything pending

2022-11-30 00:17 UTC, icehess commented
@kdamas93 I refactored the code a bit. please check the code for any semantic error or any formatting issues and etc.

the summary of changes:

* instead of passing so many arguments to function, you can simply pass the minimum argument required, here we if pass context around, we automatically have access to everything we need. This way the code is more readable.
* make simple and beautiful :))) functions that it is clear what they are doing, and give it a good name too.
* A good practice is , try to think of the logic that you are trying to implement, and see if you can encapsulate some inner of logic into smaller function, so they don't make the bigger logic hard to follow and understand. If you follow the refactored code, you see all functions related that are dealing with making request to getstream to out of main functions that deciding what do.
* Another good practice is to try and reuse code if possible, se how in the new changes related to getting and constructing the get stream field is re-used, or how the req header or url functions are re-used.
* When dealing with API, always try to return meaningful errors
* if possible try and use `kazoo_document` modules, like here we can use `kzd_users` to access user's fields

2022-12-02 19:01 UTC, kdamas93 commented
@icehess I made a few small changes that I noticed were missing while testing,
thanks in advance for the guide

2022-12-02 20:20 UTC, icehess requested changes

2022-12-02 20:20 UTC, icehess commented on src/modules/cb_getstream.erl
> +        {'ok', 200, _RespHeaders, RespBody} ->
Do not log RespBody

2022-12-02 20:20 UTC, icehess commented on src/modules/cb_getstream.erl
> +            lager:debug("getstream user created: ~p",[RespBody]),
Do not log RespBody

2022-12-02 22:13 UTC, kdamas93 commented on src/modules/cb_getstream.erl
> +            lager:debug("getstream user created: ~p",[RespBody]),
changes made!

2022-12-05 19:55 UTC, icehess approved these changes

2022-12-05 19:57 UTC, merged