KCRO-149: Implementation of Websites API
2600hz/kazoo-crossbar pull request #403
Opened 2022-12-15 16:05 UTC by Navoda626

KCRO-149: Implementation of Websites API

Implementation of websites API to facilitate adding websites using the comm.land. So an admin and users would be able to add custom websites with a logo.

A new document with the type 'website' is created in the database for every website added. 'name' and the 'web_url' are mandatory parameters for a website document and there is 'users' parameter which holds the list of users whom the website is assigned. And there is a 'account_wide' parameter works as a flag to assign the website to every user in that account.

Create, update, delete and read APIs implemented for the websites. 

Additionally a binary logo can be updated to a website document and fetched from a website document.

2022-12-15 16:31 UTC, jamesaimonetti commented on doc/websites.md
> +> GET /v2/websites
Fix

2022-12-15 16:39 UTC, jamesaimonetti requested changes
Some quick notes to start

2022-12-15 16:39 UTC, jamesaimonetti commented on doc/websites.md
> +    http://{SERVER}:8000/vs/accounts/{ACCOUNT_ID}/websites
fix version in url

2022-12-15 16:39 UTC, jamesaimonetti commented on doc/websites.md
> +            "logo": "dgsvsvasvaav",
what is the value supposed to represent? this value doesn't help me know.

2022-12-15 16:39 UTC, jamesaimonetti commented on doc/websites.md
> +## GET a website logo
why a GET to /logo when you can GET to /{WEBSITE_ID} with accept header?

2022-12-15 16:39 UTC, jamesaimonetti commented on priv/couchdb/schemas/websites.json
> +            "support_level": "supported",
don't add support_level to properties; this is more of the support team's task to do once 2600Hz "officially" supports something

2022-12-15 16:39 UTC, jamesaimonetti commented on doc/websites.md
> +Information about the websites in an account and how those websites are assigned to users.
Can you write about why websites are needed / used in KAZOO? Why would someone want or need to use this API?

2022-12-15 16:39 UTC, jamesaimonetti commented on src/modules/cb_websites.erl
> +    ?IMAGE_CONTENT_TYPES.
Should this be `?WEBSITE_LOGO_MIME_TYPES`? or is this only for content types provided by this module?

2022-12-15 16:39 UTC, jamesaimonetti commented on src/modules/cb_websites.erl
> +            lager:debug("getting system-wide summary"),
What's the usecase for system-wide? Who would access those?

2022-12-15 17:34 UTC, Navoda626 commented on doc/websites.md
> +            "logo": "dgsvsvasvaav",
This was a initial parameter used in the doc but removed later. Will remove from the .md file also

2022-12-15 17:37 UTC, Navoda626 commented on priv/couchdb/schemas/websites.json
> +            "support_level": "supported",
Will update this

2022-12-15 17:38 UTC, Navoda626 commented on doc/websites.md
> +Information about the websites in an account and how those websites are assigned to users.
Yes, will update this

2022-12-15 17:42 UTC, Navoda626 commented on doc/websites.md
> +> GET /v2/websites
will fix this

2022-12-15 17:42 UTC, Navoda626 commented on doc/websites.md
> +    http://{SERVER}:8000/vs/accounts/{ACCOUNT_ID}/websites
Will fix this

2022-12-15 18:12 UTC, Navoda626 commented on src/modules/cb_websites.erl
> +            lager:debug("getting system-wide summary"),
Yes this would not be used since admins also could see only their websites, will remove this

2022-12-15 18:17 UTC, Navoda626 commented on src/modules/cb_websites.erl
> +    ?IMAGE_CONTENT_TYPES.
Currently it supports only binary types (ex: image/png), is it better to use base64 type as well?

2022-12-15 18:23 UTC, Navoda626 commented on doc/websites.md
> +## GET a website logo
Currently implemented
POST /{WEBSITE_ID}/logo
GET /{WEBSITE_ID}/logo
GET /{WEBSITE_ID} with accept header

So is it better to use only the following?
GET /{WEBSITE_ID} with accept header
POST /{WEBSITE_ID} with content-type header

2022-12-16 18:39 UTC, icehess commented
@Navoda626 Is this API has any use outside of commland app? We have a specific app in Kazoo for commland app api, `kazoo-desktop` which i think is better place to put these commland specific APIs

2022-12-19 19:48 UTC, k-anderson commented
@icehess howdy :) so while I understand that this API is only for the comm.land desktop application, there is a target to run comm.land as a website as well as mobile.  In both the alternate deployments comm.land would NOT require kazoo-desktop (that is providing access and APIs dedicated to the desktop deployments) so I do believe crossbar is the best place for this.  IE: when Monster UI is deprecated and comm.land is the browser UI, we will have environments that us comm.land without having the desktop deployment (payed option) so the external links will need to be used without kazoo-desktop present.

2022-12-19 20:16 UTC, icehess commented
@k-anderson thanks for clarification. That make sense now.

I know this is not a good place to dicuss this, but before I forget to bring it up, how do you think about a generic storage HTTP API so any app (commland, mui, kazoo) can call it to store their custom data, like a key-store storage? I'm not saying a fully fledged S3 API but also why not? :))) Though I understand it needs the scope and some other stuff to control its security and perhaps storage space quota. 

Like here instead of creating a specific API for anything that an UI app want to persistently store, we simply provide a common generic storage and commland-core can use it store. (I'm just using this website api as an example)

2022-12-22 17:28 UTC, Navoda626 commented on doc/websites.md
> +## GET a website logo
Implemented these API removing /logo APIs
GET /{WEBSITE_ID} with accept header
POST /{WEBSITE_ID} with content-type header

2022-12-22 17:31 UTC, Navoda626 commented on src/modules/cb_websites.erl
> +    ?IMAGE_CONTENT_TYPES.
Base64 content-type is also implemented

2023-01-03 16:25 UTC, merged