KCRO-122: Screenpop endpoint to segment screenpops per user
2600hz/kazoo-crossbar pull request #408
Opened 2023-01-04 15:58 UTC by Navoda626

KCRO-122: Screenpop endpoint to segment screenpops per user

Previously there was one default screenpop per account and all the comm.land users of the account could only use that default screenpop.

Now, the screenpops can be segmented per user using the schema change (new 'permissions' object in the document schema) and a new GET accounts/{ACCOUNT_ID}/users/{USER_ID}/screenpops endpoint is implemented to get user allowed screenpops. There are 3 types of permissions for a screenpop, all_users(boolean), allow(array of user ids) and deny(array of user ids). For a specific user id if the (all_users=true OR user_id in allow array) AND (user_id NOT in deny array) that screenpop is allowed.

2023-01-04 20:25 UTC, icehess requested changes

2023-01-04 20:25 UTC, icehess commented on src/modules/cb_screenpops.erl
> +    case kz_datamgr:get_results(cb_context:account_id(Context), <<"maintenance/listing_by_type">>, Options) of
This is basic Read operation for crossbar, so please don't use `kz_datamgr` directly. Use `crossbar_view:find/4` just like `load_summary/1`. The `crossbar_view` is crossbar way which handles pagination, limit and etc.. suitable for API interface.

2023-01-04 20:25 UTC, icehess commented on src/modules/cb_screenpops.erl
> +    Options = ['include_docs'
So if you're setting `include_docs` why adding `permission` inside the [view result](https://github.com/2600hz/kazoo-core/pull/563/files#diff-ac0e3217fe1475244d7e9e3cd11e50f6f58f9209911b3a1d8481f4a92c66809dR374) then?

If you need to use the `include_docs` please consider removing `defaultValue.permissions = doc.permissions;` from view to avoid making the view big for no propose.

2023-01-04 20:25 UTC, icehess commented on src/modules/cb_screenpops.erl
> +            ModifiedSPs = [modify_screenpops_output(FilteredSP) || FilteredSP <- FilteredSPs],
Instead of all of this, if you use `crossbar_view` you can add `{'mapper', normalize_user_summary/2}` options (see `load_summary/1` too).

`crossbar_view` then automatically calls that functions and you can then filter and normalize the object however you want:

```
normalize_user_summary(JObj, Acc) ->
    AllowAll = kz_json:is_true([<<"doc">>, <<"permissions">>, <<"all_users">>], Screenpop, 'true'),
    AllowList = kz_json:get_list_value([<<"doc">>, <<"permissions">>, <<"allow">>], Screenpop, []),
    DenyList = kz_json:get_list_value([<<"doc">>, <<"permissions">>, <<"deny">>], Screenpop, []),
    case (AllowAll
        orelse lists:member(UserId, AllowList))
        andalso not lists:member(UserId, DenyList)
    of
        kz_json:get_value(<<"value">>, JObj);
....
....
....
```

2023-01-09 14:22 UTC, Navoda626 commented on src/modules/cb_screenpops.erl
> +    case kz_datamgr:get_results(cb_context:account_id(Context), <<"maintenance/listing_by_type">>, Options) of
Okay. will change that to crossbar_view:find/4

2023-01-10 14:24 UTC, Navoda626 commented on src/modules/cb_screenpops.erl
> +    Options = ['include_docs'
modified this to use crossbar_view:find/4, so not using 'include_docs' now. So the change in the view is not changed

2023-01-10 14:25 UTC, Navoda626 commented on src/modules/cb_screenpops.erl
> +            ModifiedSPs = [modify_screenpops_output(FilteredSP) || FilteredSP <- FilteredSPs],
This is changed as a normalize_user_summary

2023-01-10 21:56 UTC, icehess requested changes

2023-01-10 21:56 UTC, icehess commented on src/modules/cb_screenpops.erl
> +    Options = [{'mapper', fun (JObjs) -> normalize_user_summary(UserId, JObjs) end}
hmm, I'm not very comfortable with getting a potentially huge list of user permissions and then just looking for `true` or a single user id. Also that is why I don't like to include `permissions` in the `value` of the `crossbar_listings/by_type_id` view for screenpops.

Any idea how big this permission could be potentially become? like lets say we have 1000 users in the account, and you create a screenpops for 500 users. With this approach here:

1. the couchdb `crossbar_listings` view index file grows significantly, this reduce the speed of couchdb view and increases the disk space usage
2. to list screenpops for a single user, you are fetching a huge doc (with all those 500 user ids) and then only checking for a user id that may not even be in that list, this waste memory space and time and pressures more the db and kazoo crossbar

Always try put things on scale :)) and recognize the bottle neck. The thing i said above maybe not even happen, depends on how people use screenpops, but it still there and could cause the problem in the future.


Another approach is to create a a dedicated view just only for screenpops, and add a view that emits the a single row per `doc.permissions`. Then you can simply use this Couchdb view option to query:
```
{'keys', ['true', UserId]}
```

2023-01-11 17:56 UTC, Navoda626 commented on src/modules/cb_screenpops.erl
> +    Options = [{'mapper', fun (JObjs) -> normalize_user_summary(UserId, JObjs) end}
I agree if a separate view is defined this would be better. But at the initial discussion it was said there will be around 5 screepops per account and so that to go with the application filter rather than use map reduce function for the database.

2023-01-11 18:12 UTC, icehess commented on src/modules/cb_screenpops.erl
> +    Options = [{'mapper', fun (JObjs) -> normalize_user_summary(UserId, JObjs) end}
well i don't know anything screenpop, I was just expressing my concern here as you have more knowledge about this screenpops and its usage.

2023-01-12 19:10 UTC, icehess requested changes

2023-01-12 19:10 UTC, icehess commented on priv/couchdb/schemas/screenpops.json
> +                    "items": {
Per our discussion, please set maximum array size (50):

```suggestion
                    "maxItems": 50,
                    "items": {
```

2023-01-12 19:10 UTC, icehess commented on priv/couchdb/schemas/screenpops.json
> +                    "items": {
Per our discussion, please set maximum array size (50):

```suggestion
                    "maxItems": 50,
                    "items": {
```

2023-01-12 19:10 UTC, icehess commented on src/modules/cb_screenpops.erl
> +    Options = [{'mapper', fun (JObjs) -> normalize_user_summary(UserId, JObjs) end}
Okay, we discuss this in engineer town hall and we decided that we don't expect people set too many user ids in the array.

But also as per caution to avoid bad configuration we decide to set a maximum length for the arrays. The decide max number is 50.

 I made the suggestion code above.

2023-01-13 14:44 UTC, Navoda626 commented on priv/couchdb/schemas/screenpops.json
> +                    "items": {
This is done

2023-01-13 14:44 UTC, Navoda626 commented on priv/couchdb/schemas/screenpops.json
> +                    "items": {
This is done

2023-01-25 16:39 UTC, jamesaimonetti commented on doc/screenpops.md
> +#### Fetch all screenpops for an Account
Doc updates look great! My only ask is to add a section about the `permissions` object and state explicitly what the precedence is.

Something like, "KAZOO first considers if `all_users=true`; if so, permissions checks stop. If false, the deny list is first checked to bar the specified user explicitly. If the user isn't present in the deny list, check if the user is explicitly listed in the allow list. If not in the allow list, the user is barred."

Don't copy/paste that! But hopefully it gets the idea across; guide the client using this field on what should occur given different combinations of all_users and allow/deny lists.

2023-01-25 16:54 UTC, jamesaimonetti commented on src/modules/cb_screenpops.erl
> +                         AllowAll = kz_json:is_true([<<"value">>, <<"permissions">>, <<"all_users">>], Screenpop, 'true'),
I'd like to see the "value" pulled out and then use kzd_screeenpops:permissions_* functions to access the all_users/allow/deny values.

2023-01-26 14:31 UTC, Navoda626 commented on doc/screenpops.md
> +#### Fetch all screenpops for an Account
Will update the logic behind permissions

2023-01-26 15:00 UTC, Navoda626 commented on src/modules/cb_screenpops.erl
> +                         AllowAll = kz_json:is_true([<<"value">>, <<"permissions">>, <<"all_users">>], Screenpop, 'true'),
This is updated

2023-02-08 12:39 UTC, Navoda626 commented on src/modules/cb_screenpops.erl
> +    Options = [{'mapper', fun (JObjs) -> normalize_user_summary(UserId, JObjs) end}
Done setting maximum lengths

2023-02-08 19:05 UTC, merged