KZOO-301: Add a period of user lockout for failed login attempts
2600hz/kazoo-crossbar pull request #467
Opened 2023-04-17 16:57 UTC by dhuynh-Kazoo

Add simple account lock out mechanism using Token Buckets if any of the account's user failed to login with correct creds  in a configurable attempt tries.

2023-04-17 20:50 UTC, icehess requested changes
My assumption was that only crossbar auth modules were consuming token buckets. But after meeting with Erlang team I noticed I was wrong (well kind, but it is complicated and unrelated :))).

So instead, I suggest we add new set of functions to `cb_modules_util` for dealing with auth modules specifically.

1. `cb_modules_util:auth_bucket_names(Context, BucketNames)`:
    - This checks `Context` and adds `client_ip` (if any) to the list of passed `BucketNames`.
    - Each auth module must call this, and they have to pass a list of BucketNames.
    - These BucketNames are specific to each auth module, and depends on what they accept as payload.
    - Check each auth modules `validate` function and follow the code to see if they are expecting any payload and if yes what is the payload.
    - As bare minimum we are interested in account_id, account_name, account_realm
2. `cb_modules_util:consume_auth_tokens_until(Context, TokenCost, BucketNames)`:
    - All cb auth modules must call this instead of normal function.
    - This should iterate over bucket names and call `kz_buckets:consume_tokens_until/3` and immediately stops if it returns `false`
    - In each iteration track the bucketname and 
    - Instead of using `?APP_NAME` as first argument for `kz_buckets:consume_tokens_until/3`, use `crossbar_authenticate`. This allows us to configure how fast enough we want to fill the bucket for authentications.
    - Regardless of what `kz_buckets:consume_tokens_until/3` response is for auth buckets, also call regular `cb_modules_util:consume_tokens_until(Context, TokenCost)` to count against regular token bucket of `crossbar` so we penalty the client for the rest of endpoints too. This also set remaining token cost when the crossbar builds the response envelope.
    - the return value is is the new context updated by regular `consume_tokens_until` and a boolean indicating any of these consume tokens were false.
3. If `cb_modules_util:consume_auth_tokens_until(Context, TokenCost, BucketNames)` returns `{false, NewContext}`. stop the request and add system error, something like: `cb_context:add_system_error(401, 'invalid_credentials', <<"too many failed login attempt, your account is locked">>, Context)`
4. There were some thoughts on adding a private field to the account doc to indicate the account is locked, or other mechanism to sync all nodes on this lockout. I don't have any suggestion on this, feel free to bring this up with the rest of erlang engineers. 
5. List of auth modules by my count:
    - cb_desktop_auth (from kazoo-desktop repo)
    - cb_user_auth
    - cb_api_auth
    - cb_basic_auth
    - cb_conference_auth

Not sure @jamesaimonetti wants to add or change anything?

2023-04-17 20:50 UTC, icehess commented on src/cb_modules_util.erl
> +bucket_name({ip, IP}) -> <<IP/binary>>;
Revert this, you are changing bucket name for everything. We don't want to do that.

2023-04-19 15:00 UTC, dhuynh-Kazoo commented
hi @icehess , follow your suggestion for the function `cb_modules_util:auth_bucket_names(Context, BucketNames)`. I made some changes. Here is my idea about that:

I think each module has one bucket( I checked your comment about multiple buckets for one module and compare them in the JSON file but I am not so sure that we can have multiple buckets).

 And in my implementation, the bucket name format is `<client_ip>/<auth_module>/<client_id>` or <client_ip>/<auth_module>. The <client_id> is got from the `cb_modules_util:validate_auth_parameter`, the function may return `undefined` if client_id/account_name/account_realm are undefined, otherwise it can return any valid value. 

So at this point, we can make sure each auth module has one bucket, and based on the above Context fields, we will have the corresponding name. Please check the commit, if you have any ideas about multiple buckets, please clear it again.

2023-04-19 15:03 UTC, dhuynh-Kazoo commented
Hi @icehess, 
From your 2nd suggestion `Instead of using ?APP_NAME as first argument for kz_buckets:consume_tokens_until/3, use crossbar_authenticate. This allows us to configure how fast enough we want to fill the bucket for authentications.`. Is the `crossbar_authenticate` a new config parameter then we will add? I tried to find this keyword but I could not find it in any places in the code base.

2023-04-19 16:02 UTC, icehess requested changes

2023-04-19 16:02 UTC, icehess commented on src/cb_modules_util.erl
> +        bucket_name(cb_context:client_ip(Context), <<AuthMod/binary, "/", ValidParam/binary>>)
We want different bucket name for different parameters. creating a single bucket name consist of client ip and something else potentially like account id doesn't change anything regarding what are already doing.

Instead of creating a single bucket, return a list of bucket names:

`[client_ip, some_form_of_account_identity_like_id_realm_name_or_phone_number]`

2023-04-19 16:02 UTC, icehess commented on src/cb_modules_util.erl
> +                                   ,fun cb_context:account_realm/1
As we discuss this before, these `cb_context:account_id` and such are using the account id from URL. If you see any URL when doing authenticate there is no account id in the URL, and these always return undefined defeating the propose of what we are doing here.

```
For example for user auth
PUT /v2/user_auth

so cb_context:account_id/1 always returns undefined
```

Instead of this you have to look inside the payload
```
```suggestion
    ReqData = cb_context:req_data(Context),
    Params = [Fun(Context) || Key <-  [<<"account_id">>
                                      ,<<"account_name">>
                                      ,<<"account_realm">>
                                      ,<<"phone_number">>
                                      ],
                              Value <- [kz_json:get_ne_binary_value(Key, ReqData)],
                              Value =/= 'undefined'
             ]
```

2023-04-19 16:02 UTC, icehess commented on src/modules/cb_api_auth.erl
>          {'true', Context1} ->
Here after this line we want also to call `cb_modules:consume_auth_tokens_until/1` to check for user lockout.
```suggestion
    case cb_modules_util:consume_tokens_until(Context, TokenCost, BucketName) of
        {'true', Context1} ->
            AuthBucketNames = cb_modules_util:auth_bucket_names(Context1, []),
            case cb_modules_util:consume_auth_tokens_until(Context1, AuthBucketNames, Cost) of
                'true' ->
```

2023-04-19 16:05 UTC, icehess commented on src/modules/cb_api_auth.erl
>          {'true', Context1} ->
And then in `cb_modules_util:consume_auth_tokens_until(Context, AuthBucketNames, Cost)` will do something like this by fold over BUcketNames and calls:

```erlang
kz_buckets:consume_tokens_until(<<"crossbar_auth">>, BucketName, Cost)
```

2023-04-19 16:19 UTC, dhuynh-Kazoo commented on src/cb_modules_util.erl
> +        bucket_name(cb_context:client_ip(Context), <<AuthMod/binary, "/", ValidParam/binary>>)
Thank you for your suggestion but I imagine that for a bucket named `client_id`, we may used this bucket for all other auth modules like `cb_api_auth.erl, cb_conference_auth.erl and cb_user_auth.erl`. Is it a problem because we want to have buckets separately for each module?

2023-04-20 15:16 UTC, dhuynh-Kazoo commented on src/cb_modules_util.erl
> +        bucket_name(cb_context:client_ip(Context), <<AuthMod/binary, "/", ValidParam/binary>>)
Hi @icehess, Could you please explain the purpose that we should have multiple buckets based on each auth module? For example with cb_user_auth.erl, we only have account_name in the request payload. If the user tries with multiple account_name, the cb_modules_util:auth_bucket_names(Context, BucketNames)` may create multiple buckets. Is it worth it?

My idea is that we should have a generic bucket for all modules (we already created one from cb_modules_util:bucket_names) and a new one named <client_ip>/<auth_module> for each type of auth. Here is my draft implementation, 

First, we check if the user's request still has the remaining token in generic bucket, then we continue to check the token bucket for the current auth module 

```
consume_tokens(Context) ->
    TokenCost = cb_modules_util:token_cost(Context, ?USER_AUTH_TOKENS),
    %%  mutual bucket: created from bucket_name fun, used between modules
    %%  Auth Module: specific for each auth module
    AuthBucket = cb_modules_util:auth_bucket_name(Context, kz_term:to_binary(?MODULE)),

    case cb_modules_util:consume_tokens_until(Context, TokenCost) of
        {'true', Context1} ->
          case cb_modules_util:consume_tokens_until(Context1, TokenCost, AuthBucket) of
            {'true', Context2} -> {'ok', Context2};
            {'false', Context2} ->
              cb_context:add_system_error(401,
                'invalid_credentials',
                <<"too many failed login attempts, your account is locked">>,
                Context2)
          end;
      {'false', Context1} -> {'error', cb_context:add_system_error('too_many_requests', Context1)}
    end.

```

2023-04-20 15:33 UTC, icehess commented on src/cb_modules_util.erl
> +        bucket_name(cb_context:client_ip(Context), <<AuthMod/binary, "/", ValidParam/binary>>)
I never said we need separate bucket names for each auth module. we want ALL auth module use parameters that exists on their request data like account id, name, realm or phonenumber as a list of bucket names to consume.

2023-04-20 15:36 UTC, dhuynh-Kazoo commented on src/cb_modules_util.erl
> +        bucket_name(cb_context:client_ip(Context), <<AuthMod/binary, "/", ValidParam/binary>>)
Got it. Should we tie the client id to user parameters or just have the user parameter as the bucket name?

2023-04-20 17:14 UTC, icehess requested changes

2023-04-20 17:14 UTC, icehess commented on src/cb_modules_util.erl
> +  [cb_context:client_ip(Context) | valid_user_identities(Context)].
On second thought we don't even need client ip, remove it. move valid user identities here.

2023-04-20 17:14 UTC, icehess commented on src/cb_modules_util.erl
> +consume_auth_tokens(Context, BucketName, Cost) ->
we don't need this function remove completely.

2023-04-20 17:14 UTC, icehess commented on src/cb_modules_util.erl
> +    ].
Move this to `auth_bucket_names/1`

2023-04-20 17:14 UTC, icehess commented on src/cb_modules_util.erl
> +consume_auth_tokens_until(Context, TokenCost, []) ->
Remove this and use replace it with this:
```erlang
-spec consume_auth_tokens_until(non_neg_integer(), list()) ->
          {boolean(), cb_context:context()}.
consume_auth_tokens_until(_TokenCost, []) ->
    'true';
consume_auth_tokens_until(TokenCost, [BucketName|BucketNames]) ->
    case kz_buckets:consume_tokens_until(<<"crossbar_authenticate">>, BucketName, Cost) of
      'true' -> consume_auth_tokens_until(TokenCost, BucketNames);
      'false -> 'false
    end.
```

2023-04-20 17:14 UTC, icehess commented on src/modules/cb_api_auth.erl
> +    BucketName = cb_modules_util:auth_bucket_names(Context, kz_term:to_binary(?MODULE)),
First call regular consume_token_until (which will do it job and check bucket for `client_ip/no_account_id`.
The call if true call consume_auth_tokens_until.

as i showed before something like this:

```erlang
    case cb_modules_util:consume_tokens_until(Context, TokenCost, BucketName) of
        {'true', Context1} ->
            AuthBucketNames = cb_modules_util:auth_bucket_names(Context1, []),
            case cb_modules_util:consume_auth_tokens_until(Context1, AuthBucketNames, Cost) of
                'true' -> ....
                'false' ->
                    {'error', cb_context:add_system_error(401, 'invalid_credentials', <<"too many failed login attempt, your account is locked">>, Context1)}
```

2023-04-20 17:14 UTC, icehess commented on src/modules/cb_user_auth.erl
> -    case cb_modules_util:consume_tokens_until(Context, TokenCost) of
First call regular consume_token_until (which will do it job and check bucket for `client_ip/no_account_id`.
The call if true call consume_auth_tokens_until.

as i showed before something like this:

```erlang
    case cb_modules_util:consume_tokens_until(Context, TokenCost, BucketName) of
        {'true', Context1} ->
            AuthBucketNames = cb_modules_util:auth_bucket_names(Context1, []),
            case cb_modules_util:consume_auth_tokens_until(Context1, AuthBucketNames, Cost) of
                'true' -> ....
                'false' ->
                    {'error', cb_context:add_system_error(401, 'invalid_credentials', <<"too many failed login attempt, your account is locked">>, Context1)}
```

2023-04-24 16:05 UTC, icehess requested changes

2023-04-24 16:05 UTC, icehess commented on src/crossbar.hrl
> +-define(CROSSBAR_AUTH, <<"crossbar_auth">>).
The name of macro is too generic and confusing. it could mean anything. rename it to something like `CROSSBAR_AUTH_BUCKET`

2023-04-24 16:05 UTC, icehess commented on src/cb_modules_util.erl
> +maybe_consume_auth_tokens_until(_TokenCost, []) -> 'true';
Export this function, we need it to allow modules call this with their own list of bucket names.

2023-04-24 16:05 UTC, icehess commented on src/modules/cb_basic_auth.erl
> +            case cb_modules_util:consume_auth_tokens_until(Context1, TokenCost) of
This doesn't work here. Basic auth doesn't have any payload and `cb_modules_util:consume_auth_tokens_until/1` can't get account id.

But we do have account id. If you look further down we extract basic auth token and decode it which gives us a `[AccountId, Credentials]`.

You can refactor a bit here and do this decoding to extract any account id, if you found it then call the newly exported `cb_modules_util:consume_auth_tokens_until/3` (see the comment above) with the account id as bucket names.

2023-05-31 17:25 UTC, icehess requested changes

2023-05-31 17:25 UTC, icehess commented on src/modules/cb_security.erl
> +-spec authorize(cb_context:context(), path_token()) -> 'true' | {'stop', cb_context:context()}.
```suggestion
-spec authorize(cb_context:context(), path_token()) -> boolean() | {'stop', cb_context:context()}.
```

2023-06-02 17:38 UTC, icehess approved these changes

2023-06-02 17:40 UTC, icehess commented
Required PRs:
- https://github.com/2600hz/kazoo-crossbar/pull/467
- https://github.com/2600hz/kazoo-core/pull/663
- https://github.com/2600hz/kazoo-properly/pull/150
- https://github.com/2600hz/kazoo-desktop/pull/25

2023-06-13 15:48 UTC, icehess requested changes

2023-06-13 15:48 UTC, icehess commented on src/crossbar_auth.erl
> +    case kapps_config:is_true(?AUTH_CONFIG_CAT, <<"lock_account_on_failed_attempts">>) of
`kapps_config:is_true/2` could return `undefined`, either handle it in the case clause or use arity 3 and set a default value to `false`.

2023-09-09 00:10 UTC, jamesaimonetti commented on priv/couchdb/schemas/system_config.crossbar.auth.json
> +                    "token_auth_expiry_s": 3600
Your properly tests couldnt pass because the API to update these configs failed due to this setting being a string instead of integer() and `cb_conference_auth` missing entirely (see below change).

2023-09-12 16:15 UTC, dhuynh-Kazoo commented on priv/couchdb/schemas/system_config.crossbar.auth.json
> +                    "token_auth_expiry_s": 3600
hi @jamesaimonetti, following this I have a question: Does the change make the public conference available within one hour? As I saw this PR - [KCRO-104: Avoid conferences public links to expire](https://github.com/2600hz/kazoo-crossbar/pull/199/files), it changes `token_auth_expiry_s` to `infinity` for that purpose

2023-09-12 16:26 UTC, jamesaimonetti commented on priv/couchdb/schemas/system_config.crossbar.auth.json
> +                    "token_auth_expiry_s": 3600
Good question, I don't know. I do know the schema expects an integer() and not "infinity". Clusters can configure this setting to a year or something, to be compliant with the schema, I guess.

2023-09-18 16:37 UTC, dhuynh-Kazoo commented
Hi @jamesaimonetti , I have a concern with cb_conference_auth. I don't really touch the `token_auth_expiry_s` of the module but if I do not change the scheme, it gets validation failed.

2023-09-29 01:50 UTC, dhuynh-Kazoo commented
hi @jamesaimonetti, could you review it again? Changes were updated

2023-10-05 21:50 UTC, merged

2024-11-14 02:34 UTC, dhuynh-Kazoo commented
Backport:

[[5.4] KZOO-301: add ability to stop token bucket](https://github.com/2600hz/kazoo-core/pull/995)
[[5.4]KZOO-301: Add a period of user lockout for failed login attempts](https://github.com/2600hz/kazoo-crossbar/pull/624)