KFAX-23 : Expose parameters which required to determine file upload file size
2600hz/kazoo-crossbar pull request #468
Opened 2023-04-18 21:22 UTC by wdhammika

Previously, Support did not know what the monster UI should be updated to,  Currently, we have 3 different answers, comm.land states 15mb, the documentation states 3mb, and eFax in Kazoo report 20 MB. We are trying to track down the correct size

Two configuration parameters have been identified which determine file size.
```
crossbar => max_upload_size
fax => smtp_max_msg_size
```
Therefore `v2/accounts/{ACCOUNT_ID}/configs` has been configured to return parameters that UI needed to determine the file size and others. So UI can access those values through API.

2023-04-18 21:44 UTC, jamesaimonetti requested changes
Want to see properly test too, to verify response data

2023-04-18 21:44 UTC, jamesaimonetti commented on src/modules/cb_configs.erl
> +    [?HTTP_GET, ?HTTP_POST, ?HTTP_PUT, ?HTTP_PATCH, ?HTTP_DELETE].
I don't think this API should allow anything but GET, right?

2023-04-18 21:57 UTC, wdhammika commented on src/modules/cb_configs.erl
> +    [?HTTP_GET, ?HTTP_POST, ?HTTP_PUT, ?HTTP_PATCH, ?HTTP_DELETE].
Yes, GET is the main intention of this, but I have enabled other options to save/update parameters.

2023-04-18 22:02 UTC, jamesaimonetti commented on src/modules/cb_configs.erl
> +    [?HTTP_GET, ?HTTP_POST, ?HTTP_PUT, ?HTTP_PATCH, ?HTTP_DELETE].
These configs are global in nature and no account should be able to modify them. Please remove all but GET

2023-04-18 22:04 UTC, wdhammika commented on src/modules/cb_configs.erl
> +    [?HTTP_GET, ?HTTP_POST, ?HTTP_PUT, ?HTTP_PATCH, ?HTTP_DELETE].
Sure! I will remove them.

2023-04-19 15:21 UTC, harenson commented on priv/api/swagger.json
> +                    "description": "maximum upload file size",
What measurement unit is being used? b, Kib, Mib, Gib, etc? Please, include it within the description. Something like: `"maximum (in {MEASURE}) upload file size"`.

2023-04-19 18:14 UTC, wdhammika commented on priv/api/swagger.json
> +                    "description": "maximum upload file size",
Fixed.

2023-04-24 21:16 UTC, jamesaimonetti commented on doc/ref/configs.md
> +## Fetch
Bring this doc change down a dir to the `doc/configs.md` and add a sample response JSON payload

2023-04-25 15:57 UTC, wdhammika commented on doc/ref/configs.md
> +## Fetch
This is completed.

2023-04-25 15:59 UTC, wdhammika commented on src/modules/cb_configs.erl
> +    [?HTTP_GET, ?HTTP_POST, ?HTTP_PUT, ?HTTP_PATCH, ?HTTP_DELETE].
Added Properly test cases.
https://github.com/2600hz/kazoo-properly/pull/147

2023-05-09 21:47 UTC, merged