[master] kcro-188-ListsApiEnhancements
2600hz/kazoo-crossbar pull request #500
Opened 2023-07-11 03:43 UTC by kdamas93

The purpose of this PR is to improve/adapt the current functionality of **cb_list** to be able to save contact lists depending on the needs, with these changes it will be possible to associate **owner_id** to the lists so that they can later be filtered by user.
With this **owner_id** permission, validation logic will be added, about who can access the lists.
Multiple entries can be associated to a **list** type document, each entry will be a contact list, to achieve this it is necessary to update the current schema (**list_entry**), the documentation and its respective accessors.
It is also necessary to perform a refactor on the current code because there are functions/calls that do not follow our current programming patterns.
According to the initial meeting, it is not necessary to contemplate or carry out a treatment for the photos or vcard methods

2023-07-20 15:52 UTC, jamesaimonetti requested changes

2023-07-20 15:52 UTC, jamesaimonetti commented on priv/couchdb/schemas/list_entries.json
> +                    "contact": {
needs a `description` field

2023-07-20 15:52 UTC, jamesaimonetti commented on priv/couchdb/schemas/list_entries.json
> +                    "default": "",
no need for an empty default here, having `name` in the required section will ensure it is set to something

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +    _ = crossbar_bindings:bind(<<"*.allowed_methods.lists">>, ?MODULE, 'allowed_methods'),
Look at how cb_devices:init/0 does this, I would prefer the code is refactored in that direction.

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +    case cb_context:is_account_admin(Context)
No need for the case expression:

```erlang
maybe_admin(Context) ->
    cb_context:is_account_admin(Context)
        orelse cb_context:is_superduper_admin(Context).
```

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +            remove_lists_with_owner_id(Lists, Acc ++ [List]);
If you find yourself reaching for the append `++` operator, consider if there's a way to build the list differently. Prepending an item to a list, in Erlang, is super fast `[Item | List]` boom, done.

Appended to the end of a list means traversing `List` to add `Item` to the end, so the longer `List` is, the longer `++` takes. So this code is the absolute slowest way to build the list.

Instead, think about what this function wants to do - remove items from the list where an owner ID is set. Remove = filter. Two ways I would write that, then:

```
lists:filter(fun(List) -> kzd_lists:owner_id(List) =:= 'undefined' end, Lists)
```
This says, for each `List` in `Lists`, if the `owner_id` of `List` is undefined, return true (keep `List`); if `owner_id` returns something else, retrurn `false` (remove `List). Order of `Lists` is preserved for elements that remain.

Another option:
```
[List || List <- Lists, 'undefined' =:= kzd_lists:owner_id(List)].
```
Same thing, except as a list comprehension. Order is preserved.

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +    OwnerId = kzd_lists:owner_id(List),
Seeing the 'remove' choices above, please refactor this to not use `++` too

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +    case props:get_value(<<"users">>, cb_context:req_nouns(Context)) of
Check and see if `cb_context:user_id(Context)` returns the expected UserId

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +    io:format("~p",[cb_context:auth_user_id(Context)]),
Why `io:format`? Debug line that needs removing?

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
> +    case AuthUserId =:= UserId of
No need for the case expression

2023-07-20 15:52 UTC, jamesaimonetti commented on src/modules/cb_lists.erl
>  on_successfull_validation('undefined', Type, Context) ->
One L in successful (i know its not your typo but we may as well fix it :)

2023-07-25 15:08 UTC, kdamas93 commented on priv/couchdb/schemas/list_entries.json
> +                    "contact": {
`description `field added!

2023-07-25 15:09 UTC, kdamas93 commented on priv/couchdb/schemas/list_entries.json
> +                    "default": "",
change applied!

2023-07-25 15:09 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    _ = crossbar_bindings:bind(<<"*.allowed_methods.lists">>, ?MODULE, 'allowed_methods'),
cb_lists:init/0 refactored based on suggested module

2023-07-25 15:10 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    case cb_context:is_account_admin(Context)
change applied!

2023-07-25 15:10 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +            remove_lists_with_owner_id(Lists, Acc ++ [List]);
Thank you very much for this, I found it very useful, it has made it much easier for me, thanks for the explanation, change applied!

2023-07-25 15:11 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    OwnerId = kzd_lists:owner_id(List),
change applied!

2023-07-25 15:12 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    case props:get_value(<<"users">>, cb_context:req_nouns(Context)) of
I proceeded to use `cb_context:user_id(Context)` instead of the implemented function, which is unnecessary because the one mentioned above already exists.

2023-07-25 15:12 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    io:format("~p",[cb_context:auth_user_id(Context)]),
removed line

2023-07-25 15:13 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    case AuthUserId =:= UserId of
change applied!

2023-07-25 15:13 UTC, kdamas93 commented on src/modules/cb_lists.erl
>  on_successfull_validation('undefined', Type, Context) ->
change applied!

2023-07-31 19:01 UTC, icehess requested changes

2023-07-31 19:01 UTC, icehess commented on src/modules/cb_lists.erl
> +            NewDoc = [List || List <- RespDoc, UserId =:= kzd_lists:owner_id(List)],
Doing filtration in this way will/may breaks the pagination that `crossbar_view` tries so hardly to maintain.

I suggest either write a proper `mapper` function which checks this ownership or even create a special view `list_by_ownerid`.

You can even use a generic view like `crossbar_listings/by_ownerid_type` and use view option `{key, [UserId, <<"lists">>]}`

2023-07-31 19:01 UTC, icehess commented on src/modules/cb_lists.erl
> +            NewDoc = [List || List <- RespDoc, 'undefined' =:= kzd_lists:owner_id(List)],
This potentially breaks the pagination, please consider to either use a proper `mapper` to filter out unwanted result or use special view to `list_unowned`.

Also considering the comment in the next `case` clause, if you are using different views to list based on existence of user id, and then please move these to their own function and call `crossbar_view:load_view` with their oen view and options.

2023-07-31 19:01 UTC, icehess commented on src/modules/cb_lists.erl
> +    case cb_context:user_id(Context) of
Instead of checking authorization in validate function how about use `authorize` callback and match on method and nouns/user id?

2023-08-10 23:58 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +            NewDoc = [List || List <- RespDoc, UserId =:= kzd_lists:owner_id(List)],
proceeded to create a custom mapper for unowned lists and for owned lists a crossbar view is used

2023-08-10 23:59 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +            NewDoc = [List || List <- RespDoc, 'undefined' =:= kzd_lists:owner_id(List)],
proceeded to create a custom mapper for unowned lists and for owned lists a crossbar view is used, In the same way, it was separated into different functions since each one uses a different view.

2023-08-11 00:00 UTC, kdamas93 commented on src/modules/cb_lists.erl
> +    case cb_context:user_id(Context) of
the logic of who can access the resources was implemented in the authorize methods

2023-09-25 20:36 UTC, merged