KCRO-190: Additional APIs to consume pvt_chat.getstream in user doc
2600hz/kazoo-crossbar pull request #505
Opened 2023-07-25 15:22 UTC by Navoda626

Commland user chat feature (with the use of getstream chat APIs) is enabled by setting pvt_chat.getstream.enabled = 'true' in kazoo user document. With this change commland could use the following crossbar APIs to consume pvt_chat.getstream.

**GET accounts/{ACCOUNT_ID}/users/getstream** <-- list all user documents with pvt_chat.getstream.enabled == true

**GET accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- get the getstream object of a specific user

**PUT accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- sets pvt_chat.getstream.enabled = true and set any object in json data into getstream object for the USER_ID and return the pvt_chat.getsream object

**PATCH accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- merge the json data with pvt_chat.getstream (overwriting existing parameters including the value of enabled ) and return the pvt_chat.getsream object

**DELETE accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- removes the property pvt_chat.getstream.enabled for the USER_ID and return the deleted pvt_chat.getsream object

Properly tests:
https://github.com/2600hz/kazoo-properly/pull/172

2023-07-26 19:31 UTC, nkarunarathne commented on src/modules/cb_getstream.erl
> +    kz_json:delete_key([<<"pvt_chat">>, <<"getstream">>], Doc).
add a new line here.

2023-07-26 19:37 UTC, nkarunarathne commented on src/modules/cb_getstream.erl
> +    PatchedUser = set_chat_getstream(cb_context:doc(Context1), kz_json:merge(chat_getstream(cb_context:doc(Context1)), cb_context:req_data(Context))),
It is better to break this line down. something like this.

```suggestion
    set_chat_getstream(cb_context:doc(Context1)
		      ,kz_json:merge(chat_getstream(cb_context:doc(Context1))
		      ,cb_context:req_data(Context))
		      ),
```

2023-07-26 19:42 UTC, nkarunarathne commented on src/modules/cb_getstream.erl
> +    EnabledUser = set_chat_getstream(cb_context:doc(Context1), kz_json:set_value([<<"enabled">>], 'true', cb_context:req_data(Context))),
break this as well

2023-07-26 20:59 UTC, icehess requested changes

2023-07-26 20:59 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Context1 = crossbar_doc:load(UserId, Context),
Check the resp_status of Context1, if not success return Context1 as-is.

2023-07-26 20:59 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Context1 = crossbar_doc:load(UserId, Context),
So in all of these enable, update and delete you fetch User doc. So it is better to extract fetch user logic to its own function.  and in these functions always check of it returns success or not.

Also handle this line `[UserId] = props:get_value(<<"users">>, cb_context:req_nouns(Context)),`

It may have undefined so it is better to do:
```erlang
load_user_doc(Context) ->
    case props:get_value(<<"users">>, cb_context:req_nouns(Context)) of
        'undefined' ->
            %% return a validation error that user id is missing
        [UserId | _] ->
            crossbar_doc:load(UserId, Context)
    end.
```

2023-07-26 20:59 UTC, icehess commented on src/modules/cb_getstream.erl
> +    Context1 = crossbar_doc:load(UserId, Context),
see comment below too.

2023-07-26 20:59 UTC, icehess commented on src/modules/cb_getstream.erl
> +            crossbar_util:response_faulty_request(Context)
better to return better Message as to why it is faulty request. like say you are missing `/users` or `/users/:id` in the url.

2023-07-26 20:59 UTC, icehess commented on src/modules/cb_getstream.erl
> +            lager:debug("unexpected nouns: ~p", [_Nouns]),
remove this

2023-07-28 11:12 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +    kz_json:delete_key([<<"pvt_chat">>, <<"getstream">>], Doc).
Done

2023-07-28 11:25 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +    EnabledUser = set_chat_getstream(cb_context:doc(Context1), kz_json:set_value([<<"enabled">>], 'true', cb_context:req_data(Context))),
Got it. It's updated

2023-07-28 11:25 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +    PatchedUser = set_chat_getstream(cb_context:doc(Context1), kz_json:merge(chat_getstream(cb_context:doc(Context1)), cb_context:req_data(Context))),
Got it, thanks. Updated

2023-07-28 13:27 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +    Context1 = crossbar_doc:load(UserId, Context),
Got it, worked on this

2023-07-28 13:28 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +    Context1 = crossbar_doc:load(UserId, Context),
This is done

2023-07-28 13:33 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +            lager:debug("unexpected nouns: ~p", [_Nouns]),
@icehess would you like to remove this debug line `lager:debug("unexpected nouns: ~p", [_Nouns]),`?

2023-07-28 13:36 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +            crossbar_util:response_faulty_request(Context)
Got it. Added a meaningful message

2023-07-31 17:52 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +            lager:debug("unexpected nouns: ~p", [_Nouns]),
The log line is removed

2023-07-31 22:27 UTC, jamesaimonetti requested changes

2023-07-31 22:27 UTC, jamesaimonetti commented on src/modules/cb_getstream.erl
> +            GetstreamObj = chat_getstream(cb_context:doc(Context1)),
JSON object variable names should be `JObj` - so `GetstreamJObj` in this case

2023-07-31 22:27 UTC, jamesaimonetti commented on src/modules/cb_getstream.erl
> +                        chat_getstream_enabled(Doc)],
drop `]` to newline

2023-08-02 15:37 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +                        chat_getstream_enabled(Doc)],
This is done

2023-08-02 15:38 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +            GetstreamObj = chat_getstream(cb_context:doc(Context1)),
Got it. And changed the variable name

2023-08-07 13:29 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +    kz_json:delete_key([<<"pvt_chat">>, <<"getstream">>], Doc).
This has been resolved.

2023-08-07 13:39 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +    PatchedUser = set_chat_getstream(cb_context:doc(Context1), kz_json:merge(chat_getstream(cb_context:doc(Context1)), cb_context:req_data(Context))),
This has been resolved.

2023-08-07 13:43 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +    EnabledUser = set_chat_getstream(cb_context:doc(Context1), kz_json:set_value([<<"enabled">>], 'true', cb_context:req_data(Context))),
This has been resolved.

2023-08-07 13:51 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +    Context1 = crossbar_doc:load(UserId, Context),
This has been resolved.

2023-08-07 13:52 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +                                            ,kz_json:set_value([<<"enabled">>], 'true', cb_context:req_data(Context))
@Navoda626 it would be better if you could keep the line width below 100 characters. For such instances, break down the line.

2023-08-07 14:23 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +            crossbar_util:response_faulty_request(Context)
This has been resolved.

2023-08-07 14:24 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +            lager:debug("unexpected nouns: ~p", [_Nouns]),
This has been resolved.

2023-08-07 14:26 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +            GetstreamObj = chat_getstream(cb_context:doc(Context1)),
This has been resolved.

2023-08-07 14:26 UTC, sanjeevie6353 commented on src/modules/cb_getstream.erl
> +                        chat_getstream_enabled(Doc)],
This has been resolved.

2023-08-07 15:27 UTC, Navoda626 commented on src/modules/cb_getstream.erl
> +                                            ,kz_json:set_value([<<"enabled">>], 'true', cb_context:req_data(Context))
Thanks @sanjeevie6353 . This is updated

2023-08-11 17:41 UTC, icehess approved these changes

2023-08-11 17:59 UTC, merged