KCRO-195 : As a user I want to update date from the Monster UI entry for Marketplace connector settings
2600hz/kazoo-crossbar pull request #522
Opened 2023-10-03 19:26 UTC by manushiperera

Previously it was unable to set `is_aio_cluster` configuration through `PATCH apps_store/marketplace` API. Now this configuration can be set by `PATCH apps_store/marketplace: {"action":"enable", "settings":["is_aio_cluster",…]}`. `settings` is an optional parameter.

2023-10-03 20:48 UTC, icehess requested changes
Some notes about the shape of `settings` object.

Can you write a simple doc for this in `apps_store.md`? List of api endpoints and a sample request payload/response would be very nice.

2023-10-03 20:48 UTC, icehess commented on src/modules/cb_apps_store.erl
> +    case lists:member(<<"is_aio_cluster">>, Settings) of
Treat `Settings` as a JObj with a payload like this:

```json
{
    "action": "....",
    "settings": {
        "is_aio_cluster": boolean,
        "name": string
    }
}
```

2023-10-03 20:48 UTC, icehess commented on src/modules/cb_apps_store.erl
> +    may_be_disable_aio_cluster(cb_context:req_value(Context, <<"settings">>)),
Instead of disable/enable function have a function which parses settings (if defined) and set the name or is_aio_cluster value if they present in the jobj.

Also call this function for these actions: enable/link/api_url/update. So the UI can set any of these values in those steps if needed.

2023-10-04 21:46 UTC, manushiperera commented on src/modules/cb_apps_store.erl
> +    case lists:member(<<"is_aio_cluster">>, Settings) of
Done

2023-10-04 21:46 UTC, manushiperera commented on src/modules/cb_apps_store.erl
> +    may_be_disable_aio_cluster(cb_context:req_value(Context, <<"settings">>)),
Done

2023-10-05 06:21 UTC, icehess commented
@manushiperera I did some refactoring, to explicitly handle what setting is local and what needs to be update in appex server. There is another core pr which is required by this PR: https://github.com/2600hz/kazoo-core/pull/726

I didn't test this code, please take a time an test this. Please review the new code and fix any CI issues if there is any. If you can also please proof read the doc, I usually have a lot of typos :))

2023-10-05 16:41 UTC, icehess requested changes

2023-10-05 16:41 UTC, icehess commented on doc/apps_store.md
> +### Setting Crossbar API URl
On second thought let's remove this, and instead of update UI to use the new update action.

2023-10-05 16:41 UTC, icehess commented on src/modules/cb_apps_store.erl
>  patch_market_action(Context, ?MARKET_ACTION_API_URL) ->
On second thought let's remove this, and instead of update UI to use the new update action.

2023-10-05 16:41 UTC, icehess commented on src/modules/cb_apps_store.erl
>  validate_market_action(Context, ?MARKET_ACTION_API_URL) ->
remove this.

2023-10-10 16:50 UTC, merged