KCRO-204: As an admin I want the ability to create a JWT that only grants read access
2600hz/kazoo-crossbar pull request #549
Opened 2024-02-06 19:37 UTC by manushiperera

Previously, it was unable to grant read only access for specific users. Now, if `pvt_scopes` field is defined in `user` doc with `fetch-exclusive`, creates the JWT token that contains a claim for read only access. When JWT is authorized, check for that claim and if it presents then the request is denied if the HTTP method is not a `GET`.

2024-02-06 19:55 UTC, manushiperera commented
Related PRs
https://github.com/2600hz/kazoo-core/pull/778
https://github.com/2600hz/kazoo-properly/pull/196

2024-02-08 18:02 UTC, icehess requested changes

2024-02-08 18:02 UTC, icehess commented on src/modules/cb_token_auth.erl
> +-spec maybe_validate_scope(cb_context:context(), kz_term:api_binaries()) ->
```suggestion
-spec maybe_validate_scope(cb_context:context(), [kz_term:ne_binary() | kz_term:ne_binaries()]) ->
```

2024-02-08 18:02 UTC, icehess commented on src/modules/cb_user_auth.erl
> +            kzd_users:scope_restrictions(Doc, []) ++ kzd_users:pvt_scopes(Doc, []);
Any reason why not using `scope_restriction`?

Or any reason why using a private `pvt_scopes` field instead of publish one that can be easily added to user doc using API?

2024-02-08 18:02 UTC, icehess commented on src/modules/cb_token_auth.erl
> +    end.
You can shorten the code like this:

```suggestion
    ExpandedScopes = kz_auth_scope:to_list(kz_auth_claims:scope(JObj, [])),
    case maybe_deny_access(Context, ExpandedScopes) of
        'false' ->
            check_as(Context, JObj);
        {'true', ContextError} ->
            %% set the error in context inside maybe_deny_access/2 and return:
            %% `true | {'true', ContextError}`
            {'stop', ContextError}
    end.
```

2024-02-09 16:09 UTC, manushiperera commented on src/modules/cb_token_auth.erl
> +-spec maybe_validate_scope(cb_context:context(), kz_term:api_binaries()) ->
Done

2024-02-09 16:18 UTC, manushiperera commented on src/modules/cb_user_auth.erl
> +            kzd_users:scope_restrictions(Doc, []) ++ kzd_users:pvt_scopes(Doc, []);
`scope_restriction` is yet to be developed. Since this is an urgent requirement from Ooma, Karl advised to use `pvt_scopes`.

2024-02-09 16:18 UTC, manushiperera commented on src/modules/cb_token_auth.erl
> +    end.
Done

2024-03-04 10:29 UTC, lazedo commented
looks like this can be closed ? see comments on https://github.com/2600hz/kazoo-core/pull/778 that should also be closed.

2024-03-04 10:37 UTC, closed without merging

2024-03-04 14:39 UTC, manushiperera commented
Since we can use existing `scope_restriction` to cater this requirement, this PR is irrelevant.

First, it is required to define a scope restriction along with token restriction rule.
```
  "scopes": [
    "crossbar:read_only"
  ],
  "token_restrictions": {
    "_": [
      {
        "allowed_accounts": [
          "_"
        ],
        "rules": {
          "#": [
            "GET"
          ]
        }
      }
    ]
  }
```
Then we can use that doc id to define `scope_restrictions` in user doc.

```
{
        "last_name":"test1",
        "first_name": "test0",
        "password": "test1",
        "username": "test1",
        "scope_restrictions": [SCOPE_RESTRICTION_DOC_ID]
}
```