KCRO-218: Failure to Save Message Metadata Due to Incorrect Context Status Check in cb_vmboxes Module
2600hz/kazoo-crossbar pull request #609
Opened 2024-10-07 21:56 UTC by wdhammika

Previously, it would fail when we tried to save voicemail media messages.
Now: Handle error causes that cause problems in saving records. (Remove extra validations)

2024-10-08 16:13 UTC, icehess requested changes

2024-10-08 16:13 UTC, icehess commented on src/modules/cb_vmboxes.erl
> +    save_attachment(Context1, cb_context:req_files(Context1)).
lgtm, just please check resp_status in `put/3` before calling `maybe_save_attachment/1`

2024-10-08 19:38 UTC, wdhammika commented on src/modules/cb_vmboxes.erl
> +    save_attachment(Context1, cb_context:req_files(Context1)).
@icehess Could you please review the change?

2024-10-08 20:30 UTC, icehess approved these changes

2024-10-08 20:30 UTC, merged

2024-10-09 10:11 UTC, lazedo commented
@wdhammika @icehess I can be wrong but this pr changes nothing

2024-10-09 16:11 UTC, icehess commented
@lazedo there is also `put/5` calling `maybe_save_attachment/1` without any save operation and would fail because default context resp status is fatal.

2024-10-09 17:35 UTC, lazedo commented
@icehess so the `fix` is wrong, it should instead set rest_status on validation

2024-10-09 17:57 UTC, icehess commented
validation is fine, before execute request api_util sets resp status to fatal and all modules have to set it to success in their `put/post/delete/patch`. this module left this edge case and didn't set it.

2024-10-09 18:06 UTC, lazedo commented
isn't that what I'm saying ? the proper fix would have been to set resp_status. this all thing of putting request api_util sets resp status to fatal still hitting us, not a good change.