[master] KCRO-29: return statuses of all devices
2600hz/kazoo-crossbar pull request #63
Opened 2020-10-14 21:18 UTC by icehess

The device status API currently only returns registered devices. This change this behavior
by returning all devices, indicating registered or not when appropriate.

Additionally, some device types will never be expected to be registered. This list of device types are
stored in System Config `always_registered_device_types` in `crossbar.devices`.
By default this includes:

* application
* cellphone
* sip_url
* landline
* smartphone

Additionally, `/devices` is also changed to accept `?with_status=true` query
string so the user can request registered statues alongside listing devices to
save round trip of listing devices and requesting statues.

### Updates

* add a new fields `registrable` to indicate if device is able to register or not
* Use `registrations.search_req` for query Kamailio for list of registered devices

### Required PRs
Updating proper test: https://github.com/2600hz/kazoo-properly/pull/23
Adding kapi module for `search_req`: https://github.com/2600hz/kazoo-core/pull/110
Updating view to return sip username from: https://github.com/2600hz/kazoo-core/pull/115

2020-10-28 23:41 UTC, jamesaimonetti requested changes

2020-10-28 23:41 UTC, jamesaimonetti commented on src/modules/cb_devices.erl
> +    case {gb_sets:is_member(Id, RegIds)
Isn't this just `gb_sets:is_member(Id, RegIds) orelse lists:member(kz_json:get_value([...], JObj), RegTypes)` ?

2020-10-28 23:41 UTC, jamesaimonetti commented on src/modules/cb_devices.erl
> +-spec lookup_regs(kz_term:ne_binary(), 'sets' | 'list') -> kz_json:objects().
Can return `gb_sets:sets()` too

2020-10-28 23:41 UTC, jamesaimonetti commented on src/modules/cb_devices.erl
> +            case RetType of
What about

```erlang
            process_regs(JObjs, RetType)
     end.
 
process_regs(JObjs, 'sets') ->
    extract_device_registrations(JObjs, gb_sets:new());
process_regs(JObjs, 'list') ->
    [kz_json:from_list([{<<"device_id">>, AuthorizingId}
                       ,{<<"registered">>, 'true'}
                       ])
     || AuthorizingId <- gb_sets:to_list(process_regs(JObjs, 'sets'))
    ].

```

2020-10-28 23:41 UTC, jamesaimonetti commented on src/modules/cb_devices.erl
> +    Options = [{'doc_type', <<"device">>}
Can we use `kzd_devices:type()` in these places where the doc type is used?

2020-10-28 23:41 UTC, jamesaimonetti commented on doc/devices.md
> +            "registered": true
Personally I'm not crazy on the idea of `registered: true` for non-registering devices. Seems like we have a tristate situation: `is_registered`, `not_registered`, `doesnt_register`. Not sure the best format to represent this enum for JSON. Thoughts?

2020-11-02 17:41 UTC, joristirado commented on doc/devices.md
> +            "registered": true
How about the absence of the `registered` prop to denote devices that can't register?

2020-11-02 18:13 UTC, jamesaimonetti commented on doc/devices.md
> +            "registered": true
Perhaps two keys?:
1. `registered: true, registerable: true` - when registered
2. `registered: false, registerable: true` - when not registered
3. `registerable: false` - when not applicable

Or LISPy `registersp` :)

2020-11-16 18:52 UTC, jamesaimonetti commented
Added test https://github.com/2600hz/kazoo-properly/pull/29 for non-registering devices too

2020-11-16 19:26 UTC, merged