PROD-257: adding an API to create a link for conference
2600hz/kazoo-crossbar pull request #67
Opened 2020-10-23 19:45 UTC by icehess

Adding public conference API endpoint.

This endpoint will be used to authenticate a conference or create an invite link for concference:
* If the request has already authenticated, generate the a JWT and a link to public conference domain
* If the request is not authenticated, ask for a conference name, pin number and account name then generate JWT

This Auth token then can used to request Verto/Conference bridge info from desktop API.

> **NOTE:** With these changes we now make Conference name required. This name MUST be unique in the account.

Also add `conference_public_domain` field to whitelabel document.

### Required PRs:
probably needs more PR to fix scopes and adding `conference_join` scope.

### Circular PR dependency
Adding conference_auth accessors: https://github.com/2600hz/kazoo-core/pull/111
Changing conference test: https://github.com/2600hz/kazoo-properly/pull/28

2020-11-10 19:42 UTC, jamesaimonetti requested changes

2020-11-10 19:42 UTC, jamesaimonetti commented on doc/whitelabeling.md
> +`conference_public_domain` | This is the whitelabeled domain that confrence participants can use to reach the conference through webphone | `string()` |   | `false` | `supported`
splchk confrence :)

2020-11-10 19:42 UTC, jamesaimonetti commented on priv/couchdb/schemas/conferences.json
> +        "public_link_enabled": {
Should it be `public_link_enabled` or maybe something like `allow_public_participants` or??

2020-11-10 19:42 UTC, jamesaimonetti commented on src/crossbar_maintenance.erl
> +-spec ensure_conferences_db() -> 'no_return'.
Could this be part of cb_conference_auth's init/0?

2020-11-10 19:42 UTC, jamesaimonetti commented on doc/conference_auth.md
> +    http://{SERVER}:8000/v2/accounts/{ACCOUNT_ID}/conference_auth/{CONFERENCE_ID}
Curious, why not add the auth stuff to cb_conferences? `/v2/accounts/{ACCOUNT_ID}/conferences/{CONFERENCE_ID}/link` or something? I'm not sure why a new module is necessary?

2020-11-10 19:42 UTC, jamesaimonetti commented on src/modules/cb_conference_auth.erl
> +            cb_context:build_system_error(401, <<"invalid_conference">>, <<"invalid conference">>, Context)
This function isn't exported?

2020-11-10 19:42 UTC, jamesaimonetti commented on src/modules/cb_conferences.erl
> +-spec invalid_unique_name(cb_context:context(), kz_term:ne_binary()) -> kz_term:ne_binary().
Returns `cb_context:context()`

2020-11-10 19:42 UTC, jamesaimonetti commented on src/modules/cb_conferences.erl
> +          {'ok', []} |
Why is success either the empty list or a JSON object? That is odd, no?

2020-11-10 19:42 UTC, jamesaimonetti commented on src/modules/cb_conferences.erl
> +          {'ok', []} |
`kz_term:api_object()` seems more consistent with the project.

2020-11-13 19:45 UTC, icehess commented on doc/whitelabeling.md
> +`conference_public_domain` | This is the whitelabeled domain that confrence participants can use to reach the conference through webphone | `string()` |   | `false` | `supported`
You have eagle eye catching typos? :)

2020-11-13 19:46 UTC, icehess commented on priv/couchdb/schemas/conferences.json
> +        "public_link_enabled": {
I think I would rename this to `allow_shareable_link`. Shareable link it what UI calls it. Idea?

2020-11-13 19:48 UTC, icehess commented on src/crossbar_maintenance.erl
> +-spec ensure_conferences_db() -> 'no_return'.
This db is getting remove. We decide to include account name the login page so no need for cluster-wise unique name anymore.

2020-11-13 19:51 UTC, icehess commented on doc/conference_auth.md
> +    http://{SERVER}:8000/v2/accounts/{ACCOUNT_ID}/conference_auth/{CONFERENCE_ID}
Because the are two scenario:

1) You have been invite to the conference by a link which already has the valid JWT token
2) You go to the conference public domain, and then login with conf name, account name and pin number

Because of number 2 above, we decided to create a new auth module specifically for logging in to conference.

2020-11-16 23:20 UTC, jamesaimonetti commented on doc/conference_auth.md
> +    http://{SERVER}:8000/v2/accounts/{ACCOUNT_ID}/conference_auth/{CONFERENCE_ID}
Gotcha, right on

2020-11-18 19:34 UTC, merged