PISTON-1143: Reconciles the voicemail schema documentation.
2600hz/kazoo-crossbar pull request #69
Opened 2020-10-30 21:05 UTC by tetrachromium

At some point, the `voicemail` document was renamed as `vmboxes`, but the related documentation files were not  renamed to match. As a result, a hand-edited `voicemail.md` document diverged considerably from the auto-generated `ref/vmboxes.md` document. The contents of the `voicemail.md` have been reordered to reduce the degree of difference from the auto-generated file, and some minor corrections were made to the text.

Kazoo 4.3 pull request: https://github.com/2600hz/kazoo/pull/6656

2020-10-30 21:06 UTC, tetrachromium commented
Looking at the differences within the `voicemail.md` file is likely to just be confusing. To understand the reasons for the changes and check for correctness, the revised `voicemail.md` file should be compared with the `ref/vmboxes.md` file. I suspect that the amount of difference between the two files has crept in due to the fact that they no longer have the same name. It was a while before I realized the two files were related. If you are willing to rename the file and redirect from the old URL, let me know and I will do that as a separate commit.

2020-11-20 19:36 UTC, icehess requested changes

2020-11-20 19:36 UTC, icehess commented on doc/voicemail.md
> +In the first method, you can create a voicemail document first in one request and then put the media file into the document with a second request using `/messages/{VM_MSG_ID}` API endpoint.
It is actually `PUT /messages/{VM_MSG_ID}/raw`.

2020-11-20 19:36 UTC, icehess commented on doc/voicemail.md
> +In the first method, you can create a voicemail document first in one request and then put the media file into the document with a second request using `/messages/{VM_MSG_ID}` API endpoint.
make a link to the section:

```
[`/messages/{VM_MSG_ID}/raw`](create-the-raw-audio-for-a-voicemail-message)
```

2020-11-20 19:36 UTC, icehess commented on doc/voicemail.md
> +And then you can use PUT method on `/messages/201605-fadnew0mf6fcfgfd8bcdfca312e924bq` to add the media to file (see PUT method for a message below).
same as above it has `/raw` at the end

```
[`/messages/{VM_MSG_ID}/raw`](create-the-raw-audio-for-a-voicemail-message)
```

2020-11-20 19:36 UTC, icehess commented on doc/voicemail.md
> +With pagination:
It should do pagination by default. Did you mean **without** pagination?

2020-12-01 17:33 UTC, tetrachromium commented on doc/voicemail.md
> +With pagination:
The query parameter is `pagination=true` so "without pagination" wouldn't seem to make much sense. My goal is simply to get this file to more or less match the `ref` version of the file again. If there are documentation errors, they were there already. You will have to tell me what corrections you want or can make them yourselves after this is merged.

2020-12-02 00:10 UTC, tetrachromium commented on doc/voicemail.md
> +In the first method, you can create a voicemail document first in one request and then put the media file into the document with a second request using `/messages/{VM_MSG_ID}` API endpoint.
Changed.

2020-12-02 00:11 UTC, tetrachromium commented on doc/voicemail.md
> +And then you can use PUT method on `/messages/201605-fadnew0mf6fcfgfd8bcdfca312e924bq` to add the media to file (see PUT method for a message below).
Changed.

2021-01-20 01:21 UTC, icehess approved these changes

2021-01-20 01:21 UTC, merged